### ISSUE TITLE
[no-passed-in-event-handlers] Add whitelist support

### ISSUE THREAD

**Issue by boris-petrov** [ember-template-lint/ember-template-lint#1034]
Two usecases:

1) I have a component that inherits from the built-in `link-to` component. There is no easy way of circumventing passing `@click=...`.

2) I have a Glimmer component which just happens to have a callback named `click`.

In both of these cases I would like to suppress the `no-passed-in-event-handlers` warning because it is not "correct".

**Comment by rwjblue** [comment]
The idea seems reasonable to me, we need to come up with a nice configuration API for it.

**Comment by boris-petrov** [comment]
hm, I believe this has been implemented by #1857, right? Thanks!
