### ISSUE TITLE
Cannot read property `length` of undefined undefined

### ISSUE THREAD

**Issue by lifeart** [ember-template-lint/ember-template-lint#1065]
ember-template-lint 1.8.1

![image](https://user-images.githubusercontent.com/1360552/71993856-d91fde80-3248-11ea-90e9-efe1e8033507.png)

**Comment by lifeart** [comment]
@rwjblue should we improve error reporting, specifying "broken" rule?
Also, I was thinking about integrational tests for all rules to catch such issues.

**Comment by bmish** [comment]
You can run `ember-template-lint --verbose` to find out what rule is causing the error.

**Comment by lifeart** [comment]
@bmish thank you! 
![image](https://user-images.githubusercontent.com/1360552/72002218-0d4ecb80-3258-11ea-81dd-4233c550945c.png)

Looks like issue should be fixed in https://github.com/ember-template-lint/ember-template-lint/commit/7a95fcf87a2f90773b6e0c10deb5f364aea05b21#diff-29931e7900ce80519d8178889105564d
