### ISSUE TITLE
New rule which forces using @-prefixed attributes in native components

### ISSUE THREAD

**Issue by stukalin** [ember-template-lint/ember-template-lint#1098]
In the https://api.emberjs.com/ember/release/classes/Ember.Templates.components/methods/Input?anchor=Input we have the following section

> However, there are a few attributes where you must use the @ version.

which tells us to use the `@` for (at the moment of writing) `@type`, `@value` and the `@checked` on the `<Input/>`. Can we add a rule to enforce that?

**Comment by lifeart** [comment]
should rule warn if `{{on 'change' this.change}}` modifier used on `<Input | Textarea> `?

**Comment by stukalin** [comment]
@lifeart could you remind me what's wrong with that `{{on 'change'}}` ?

**Comment by lifeart** [comment]
it's framework component, I beleve developers should use `@onchange={{this.callback}}` to handle changes.

**Comment by stukalin** [comment]
@lifeart sounds like a bit off-the-scope of the proposed rule to me. Not 100% sure though

**Comment by rwjblue** [comment]
Ya, agree with @stukalin. I think adding a rule to help folks use `<Input>` properly makes sense.
