### ISSUE TITLE
Argument / Attribute sorting rule

### ISSUE THREAD

**Issue by Windvis** [ember-template-lint/ember-template-lint#1099]
Our company has the policy to sort all arguments / attributes alphabetically to prevent bikeshedding about it. It would be nice if there was a rule to enforce this, so we wouldn't have to spend time on it during code reviews :smile:.

I'm not 100% sure how this should work. Should HTML elements be treated differently from component invocations?

**Comment by dcyriller** [comment]
@Windvis there is a work in progress here: https://github.com/ember-template-lint/ember-template-lint/pull/871

**Comment by Windvis** [comment]
Oh, I'm sorry. Note to self, use more than 5 minutes to look for related issues 😄.
