### ISSUE TITLE
Error messages should contain rule code

### ISSUE THREAD

**Issue by lolmaus** [ember-template-lint/ember-template-lint#1128]
It's quite difficult to figure out a linting error, because the error message does not contain a rule code, and the rule's documentation page does not contain the error message.

As a result, you can't easily look up a documentation page for your linting error.

So your only option is to google up the error message, hoping that someone on the internet has mentioned which rule it corresponds to.

![image](https://user-images.githubusercontent.com/200884/75008684-c1fc1f80-5489-11ea-8553-73455f202779.png)

Other linters for comparison:

![image](https://user-images.githubusercontent.com/200884/75008569-6b8ee100-5489-11ea-88f8-eebd1db7d80c.png)

![image](https://user-images.githubusercontent.com/200884/75008634-9da04300-5489-11ea-9bbc-0b58052dc2c7.png)

**Comment by rwjblue** [comment]
This seems like an editor extension issue to me, both the default format and `--json` format output of our bin script include the rule name in their output. The message itself should not _also_ contain the rule name.

Probably best to file an issue on whatever extension you are using in your editor that wraps ember-template-lint, to ask them to include the rule name in the visuals.

**Comment by lifeart** [comment]
![image](https://user-images.githubusercontent.com/1360552/75065030-1094d280-54f9-11ea-8901-f8b851ee1077.png)
VSCode unstable language server fixed in "0.3.8"

**Comment by lolmaus** [comment]
:heart:
