### ISSUE TITLE
no-quoteless-attributes false positives after upgrading

### ISSUE THREAD

**Issue by jacobq** [ember-template-lint/ember-template-lint#1135]
Wanted to put this here for anyone encountering this issue after running `yarn upgrade` (and getting `ember-template-recast` v4.1.0)

https://github.com/ember-template-lint/ember-template-recast/issues/221

**Comment by rwjblue** [comment]
This affects users of ember-template-lint@2.0.0-beta.5 (any of the 2.0.0-beta series really), and was fixed by https://github.com/ember-template-lint/ember-template-lint/pull/1123. I'll try to get another beta release out so folks aren't bitten by the interim state.

**Comment by rwwagner90** [comment]
I'm seeing this issue as well. Isn't 2.x not beta anymore? I'm on 2.0.1, with not `beta` in the tag.

**Comment by jacobq** [comment]
Different packages
ember-cli-
ember-

**Comment by rwjblue** [comment]
Oh no! I didn't realize that ember-cli-template-lint@2.0.0 (stable, not beta) was out but still using ember-template-lint@2.0.0-beta.x.

**Comment by rwjblue** [comment]
Released 2.0.0 with the fixes mentioned, sorry about this y'all...

**Comment by rwwagner90** [comment]
Thanks @rwjblue! Appreciate the quick turnaround 😃

**Comment by rwwagner90** [comment]
It seems like maybe something didn't get published correctly? I am on ember-cli-template-lint 2.0.2 and still seeing this issue.

**Comment by rwjblue** [comment]
Hmm, can you make a reproduction?

**Comment by rwwagner90** [comment]
The issue I was hitting was in ember-shepherd. If you pull it down and remove the disabling of the rule here https://github.com/shipshapecode/ember-shepherd/blob/master/.template-lintrc.js#L8 it should show the errors.
