### ISSUE TITLE
Does ember-template-lint v2 support ESLint integration?

### ISSUE THREAD

**Issue by richard-viney** [ember-template-lint/ember-template-lint#1161]
Looking at upgrading to v2 and ran into an ESLint issue on the following code:

```typescript
import hbs from "htmlbars-inline-precompile"

hbs`<MyComponent />`
```

which gives the following output when running ESLint:

`
3:1  error  3 error(s): The "path" argument must be of type string. Received type undefined  hbs/check-hbs-template-literals
`

Is the ESLint integration intended to work with v2 yet? I did notice
`warning " > eslint-plugin-hbs@1.0.0" has incorrect peer dependency "ember-template-lint@^1.5.3".` when installing, so perhaps this isn't supported yet.

My `.template-lintrc.js` is:

```javascript
module.exports = {
  extends: ["recommended", "octane", "stylistic"],

  rules: {
    "attribute-indentation": false,
    "eol-last": "always",
    "inline-link-to": true,
    "modifier-name-case": true,
    "no-bare-strings": true,
    "no-implicit-this": { allow: ["rootURL"] },
    "no-invalid-interactive": false,
    "require-valid-alt-text": false,
    "template-length": { max: 275, min: 1 }
  }
}
```

Thanks!

**Comment by bobisjan** [comment]
This was introduced by [fix](https://github.com/ember-template-lint/ember-template-lint/pull/1072) for EdtiorConfig. So yes, the `eslint-plugin-hbs` needs to be updated to be compatible with `2.0.1+`, there is already open [PR](https://github.com/ember-template-lint/eslint-plugin-hbs/pull/35) for that.

**Comment by rwjblue** [comment]
I've submitted https://github.com/ember-template-lint/ember-template-lint/pull/1167 to ensure that we don't error here (https://github.com/ember-template-lint/eslint-plugin-hbs/pull/35 is still needed, but I didn't want ember-template-lint itself to error like this regardless).
