### ISSUE TITLE
update contributing.md 

### ISSUE THREAD

**Issue by MelSumner** [ember-template-lint/ember-template-lint#1164]
once #1103 and #1163 are merged, update the CONTRIBUTING.md file and pull out the contributing info  that will be in dev/new-rule/index.js and the README into the CONTRIBUTING file.

**Comment by rwjblue** [comment]
#1163 is landed, so we can probably update `CONTRIBUTING.md` directly in #1103 instead of the `README.md`.

Closing (please reopen if I've missed something...)
