### ISSUE TITLE
Document the rule test harness.

### ISSUE THREAD

**Issue by rwjblue** [ember-template-lint/ember-template-lint#1170]
The test harness is exported in `lib/` so that folks can leverage it to run their plugins's tests. It is a really awesome feature!

But we don't have documentation for it in our README.md or the `docs/` subdir (there are some nice API docs though).

**Comment by bmish** [comment]
Now documented in: https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/plugins.md#rule-tests
