### ISSUE TITLE
Move simpler functions from `get-config` into a separate file

### ISSUE THREAD

**Issue by suchitadoshi1987** [ember-template-lint/ember-template-lint#1194]
Currently, with #1160 PR, we have to dynamically load `get-config.js` in `base.js`. This is because `get-config.js` depends on `rule.js` and if we import `get-config.js` from `base.js`, it creates a circular dependency issue with modules (https://nodejs.org/api/modules.html#modules_cycles).
Hence, to avoid this, and to make things more clear, there are certain functions that are simple enough to live in a separate file so that other modules can take advantage of the same.

**Comment by locks** [comment]
I investigated this and as far a I could find, there is no longer a loop, so I'm closing this issue!
