### ISSUE TITLE
Add ability to lint .html files

### ISSUE THREAD

**Issue by MelSumner** [ember-template-lint/ember-template-lint#1230]
Adding the ability to lint the `.html` files as well as the `.hbs` files. This would allow us to check for the language attribute on the body element, among other things. 

Relevant area of the codebase: https://github.com/ember-template-lint/ember-template-lint/blob/0acaf3513857203c90ae973f76446ecfc61700d1/bin/ember-template-lint.js#L37

Newly generated ember-cli apps use `ember-template-lint .` as part of their `lint:hbs` `package.json` script. This illustrates why making `ember-template-lint` allow `.html` files would be a breaking change (see our [versioning policy](https://github.com/ember-template-lint/ember-template-lint/blob/master/dev/versioning.md) for more details).

General path forward:

1. Allow consumers to **explicitly** pass globs that include/allow for `.html`. At this stage, calling `ember-template-lint **/*.*` would lint against HTML files but `ember-template-lint .` or `ember-template-lint app/templates` (specifying a non-glob path) would not. This can be released without a major version bump.
2. Test to ensure that our linting rules do not flag issues with a newly generated ember-cli app's `index.html`. Fix any issues identified (either with rule changes, or with ember-cli changes).
3. Change the default globbing patterns to allow `.html` by default. This is the breaking change, and requires a major version bump.

**Comment by Turbo87** [comment]
https://github.com/glimmerjs/glimmer-vm/issues/870 might be relevant for this issue 🤔

**Comment by rwjblue** [comment]
@MelSumner - Can you review to confirm if this is fully resolved now?

**Comment by MelSumner** [comment]
this is indeed resolved with #1232 and improved with #1631 . Closing issue.
