### ISSUE TITLE
GitHub annotations does not distinguish between warnings and errors

### ISSUE THREAD

**Issue by chancancode** [ember-template-lint/ember-template-lint#1245]
1. GitHub supports [warning messages](https://help.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-a-warning-message) in addition to errors, but we have [hardcoded it to use the error format](https://github.com/ember-template-lint/ember-template-lint/blob/master/lib/printers/github-actions.js#L30) regardless of severity. Since we have the information, we should use it.

2. Related: pending rules are currently emitted as warnings. IMO this is not great even for development, but regardless, I think they should be omitted from the GitHub reporter specifically, otherwise these files will be flagged for every single CI run. IIRC, we already have code that turns them into errors when the module clears all the pending rules, so there is no worries about missing them here.

**Comment by eramod** [comment]
Just FYI, I'm working on this.

**Comment by chancancode** [comment]
another related issue: the GitHub Actions printer does not respect the `--quiet` flag

**Comment by rwjblue** [comment]
> but we have hardcoded it to use the error format  regardless of severity.

Ya, we only recently (ish) landed proper severity support. I missed this when thinking about that PR, sorry about that!

> the GitHub Actions printer does not respect the --quiet flag

Ya, definitely should be fixed up.

**Comment by rwjblue** [comment]
> related: pending rules are currently emitted as warnings.

@chancancode - I actually think this is a bit of a separate issue from the other two things (which are clearly bugs and whatnot). Would you mind making a separate issue RE: pending rule failures being warnings?

**Comment by chancancode** [comment]
Sure I'll spin that off to another issue.

**Comment by chancancode** [comment]
Closed by #1257
