### ISSUE TITLE
Pending rules should not be printed as warnings by default

### ISSUE THREAD

**Issue by chancancode** [ember-template-lint/ember-template-lint#1248]
Having all the pending rules printed to the output as warnings is not a useful default in my opinion. It drowns out any other non-pending warnings, and encourages the developer to form a habit in ignoring the output in general. Since we already fails the lint when a pending rule become fixed, there is very little value in continuously reminding the developer about them in the mean time. I think they should be hidden by default, and a `--verbose` flag or something can turn them on if desired.

**Comment by rwjblue** [comment]
Seems good to me, though I do think _seeing_ those things is useful in editor plugins. Perhaps we could use severity `0` (instead of `1` for warning or `2` for errors). :thinking:

**Comment by chancancode** [comment]
Based on #1245 (`--quiet` flag has no effect in GH Actions), it seems like the editor plugins may already not be bound by the same rules as the default CLI printer. But if they are, they can just invoke the tool with the equivalent of `--verbose` mode internally, right? I agree it may be nice in theory for them to be able to distinguish between pending and warning, but I'm not sure if the editors actually support more than two levels of severity. I think vscode doesn't, for example, and I think by including the pending rules they may get added to the "Problems" panel and be super noisy.

**Comment by chancancode** [comment]
@rwjblue how should we move forward with this? not too sure how editors integrate with this, so unsure if the `--verbose` proposal work for them

**Comment by rwjblue** [comment]
I dunno. I don't feel overly strongly here. I think we should still emit the pending items internally, but I don't think it's terribly important for the normal out of hte box bin script output to include them as warnings in the console.

**Comment by allison-strandberg** [comment]
Just wanted to confirm @chancancode's suspicion: in VSCode, I'm seeing errors appear in the Problems panel for rules in pending modules and it introduces a lot of noise.

**Comment by rwjblue** [comment]
Ya, I think we can make them not warnings and then add a command line option to toggle that (or to just print out pending issues). Happy to help shepherd a PR forward that does this.

**Comment by chancancode** [comment]
I think @eramod is interested in picking this up 👌

**Comment by eramod** [comment]
I am! @rwjblue Can you give me more details on what you'd like done?

**Comment by chancancode** [comment]
Any of these seems fine to me. Although a “no pending” flag can have an unfortunately ambiguous sounding name (can me the opposite of “pending”, whatever that means, or “do not allow check to pass if there are any pending rules left”). Related, we also need to think about exit codes in the options you presented, yeah? Do we just exit with nonzero in any of the options you proposed when there are pending rules? It seems fine to me but not sure if there are other also valid designs there.

In terms of implementation I agree number 3 is probably the closest so if @eramod wants to get a headstart I think that’s a good starting point.

**Comment by rwjblue** [comment]
Planning to tackle this as part of #1557.

**Comment by locks** [comment]
This has been addressed as part of the todo feature implementation.
