### ISSUE TITLE
Rule request: add condition to `require-input-label` rule

### ISSUE THREAD

**Issue by MelSumner** [ember-template-lint/ember-template-lint#1256]
## Context
Currently, the `require-input-label` rule does not check for instances where a valid label has already been provided but another label is associated with the input element through the use of the `aria-labelledby` attribute. 

We could update the `require-input-label` rule or create a separate rule called `no-duplicate-label`. 

## Task
Update the rule so it checks for redundant labels- if the `<input>` element already has an associated `<label>` element, it does not require the `aria-label` or `aria-labelledby` attributes.

### Not okay 
```html
    <label for="input-search">Search</label>
    <input type="text" aria-labelledby="button-search" id="input-search" />
    <button id="button-search" type="button">Search</button>
```

### Okay 
```html
    <input type="text" aria-labelledby="button-search" />
    <button id="button-search" type="button">Search</button>
```

**Comment by KamiKillertO** [comment]
I can have a look at this one

**Comment by MelSumner** [comment]
@KamiKillertO what do you think?

**Comment by KamiKillertO** [comment]
I've had a look but I haven't been able to make it work yet. But after reading the example again I might have an idea 🤔

**Comment by KamiKillertO** [comment]
@MelSumner I've opened a draft PR.

**Comment by KamiKillertO** [comment]
@MelSumner the PR has been merged, should we close this issue too?

**Comment by MelSumner** [comment]
@KamiKillertO good catch! Thank you for doing this work! 👍🏻
