### ISSUE TITLE
Rule request: ensure landmark elements do not have redundant roles

### ISSUE THREAD

**Issue by MelSumner** [ember-template-lint/ember-template-lint#1273]
If a landmark element is used, any role provided will either be redundant or incorrect. Add support for landmark elements to ensure that no role attribute is placed on any of the landmark elements, with a few exceptions. 

## List of elements & their corresponding roles
- header (banner)
- main (main)
- aside (complementary)
- form (form, search)
- main (main)
- nav (navigation)
- footer (contentinfo)

## Exceptions

- form (can have role of search)
- footer (can have role of contentinfo)

**Comment by rajasegar** [comment]
@MelSumner I am picking this up, can you please assign it to me?
