### ISSUE TITLE
Feature: allow custom reporters

### ISSUE THREAD

**Issue by gabrielcsapo** [ember-template-lint/ember-template-lint#1339]
It would be great to allow reporters with the same interface as eslint. https://eslint.org/docs/developer-guide/working-with-custom-formatters

Is this something that would be accepted?

**Comment by lifeart** [comment]
related issue: https://github.com/ember-template-lint/ember-template-lint/issues/616

**Comment by gabrielcsapo** [comment]
@lifeart I saw those as being specific internal asks for output formats. My request was more generic in that fact that the reporters could be decided via cli arguments.

**Comment by rwjblue** [comment]
Ya, I definitely want to do some variation here. The internal structure makes it fairly easy to actually do. We’d just need to ensure:

* that the input format is properly specified 
* the command line option is not breaking 
* the existing system (default printer, GitHub actions printer, JSON printer) is well rationalized in terms of the new capabilities

**Comment by gabrielcsapo** [comment]
@rwjblue i had a use case today pop up to format data for a report, will out something together that takes existing functionality and will abstract to allow new use cases
