### ISSUE TITLE
Rule-request: no yield to default

### ISSUE THREAD

**Issue by chancancode** [ember-template-lint/ember-template-lint#1352]
```hbs
{{yield ... to="default"}} -> {{yield ...}}
{{has-block "default"}} -> {{has-block}}
{{has-block-params "default"}} -> {{has-block-params}}
{{hasBlock "default"}} -> {{hasBlock}}
{{hasBlockParams "default"}} -> {{hasBlockParams}}
```

**Comment by rwjblue** [comment]
Yep. We should definitely do this, especially as named blocks roll out. Per a quick search on ember observer I don’t think anyone is currently using `to=“default”` but with named blocks folks may start trying it out.

**Comment by rajasegar** [comment]
@rwjblue @chancancode I am interested in picking this one, can you please assign it to me?
