### ISSUE TITLE
Remove automatic TextNode unwrapping in `AstNodeInfo.elementAttributeValue`

### ISSUE THREAD

**Issue by rwjblue** [ember-template-lint/ember-template-lint#1358]
The fact that `AstNodeInfo.elementAttributeValue` automatically unwraps `TextNode` values makes it **very very** easy to miss the fact that it _might_ return a plain string **OR** an AST node. This leads to common errors where folks treat the value like a string, and then assume they can use string methods on the value (since all of the tests added _happen_ to not use a dynamic value).

Examples issues:

* https://github.com/ember-template-lint/ember-template-lint/issues/1286
* https://github.com/ember-template-lint/ember-template-lint/pull/1327

**Comment by scalvert** [comment]
Does #1388 fully cover this issue, @rwjblue?
