### ISSUE TITLE
Remove rule "no-unnecessary-component-helper"

### ISSUE THREAD

**Issue by everydaypanos** [ember-template-lint/ember-template-lint#1360]
Hi,
The rule "no-unnecessary-component-helper" does not take into account cases where a component renders inline elements (svg, img etc). In these cases code formatters/beautifiers break the inline portion of the text into multiple lines and thus producing a different result than intended.

FOR EXAMPLE

CODE BEFORE BEAUTIFIER
```
<p>Hi, this is a sentence with an {{component "that-renders-svg-icon"}}.</p>
```
CODE AFTER BEAUTIFIER
```
<p>Hi, this is a sentence with an {{component "that-renders-svg-icon"}}.</p>
```
RESULT
```
<p>Hi, this is a sentence with an <svg>...</svg>.</p>
```

CODE BEFORE BEAUTIFIER
```
<p>Hi, this is a sentence with an <ThatRendersSvgIcon />.</p>
```
CODE AFTER BEAUTIFIER
```
<p>Hi, this is a sentence with an
<ThatRendersSvgIcon />
.</p>
```
RESULT
```
<p>Hi, this is a sentence with an <svg>...</svg> .</p>
```

**Comment by rwjblue** [comment]
Ya, I don't really see this as a bug in the ember-template-lint rule so much as a bug in the beautifier that you are using (what is it?).

**Comment by everydaypanos** [comment]
It happens both on VSCode default formatter and on JSBeutifier extension also on VSCode. I think that all HTML/HBS formatters work the same way: Every non-inline tag is out on a new line.

**Comment by rwjblue** [comment]
The issue here is that this _really_ has nothing to do with the lint rule, you just happen to be able to use this trick to avoid the formatting change. Fundamentally, if you put the same HTML content in that location (e.g. you don't actually have a component being invoked) you have the same problem.

**Comment by everydaypanos** [comment]
_It should not exist._

The point is that it breaks the development process! Of course if you put a DIV instead of an ember component you will have the same "fundamental" problem. But my problem is with the coding part of the ember app not with the HTML spec itself!

I guess 90% of Ember apps are coded with code formatters/beautifiers and this rule simply is too far reaching. I just showed you an example where it obviously "breaks" the end result during coding..

All I'm saying here is that there are cases where you really want to use the mustache-helper to render a component.

Thanks!
