### ISSUE TITLE
Audit rule documentation to ensure all relevant references are included

### ISSUE THREAD

**Issue by MelSumner** [ember-template-lint/ember-template-lint#1368]
In reviewing documentation for each rule, I discovered that many rules are missing links to specifications or other documentation that provides the justification for each rule. 

To correct this issue, a references section for each rule should be added. 

For a rule that successfully lists references, see [require-input-label](https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/require-input-label.md)

**Comment by rwjblue** [comment]
@MelSumner - This issue is not terribly actionable at the moment. If you did an audit, can you update this issue description with a list of rules needing tweaks?

**Comment by MelSumner** [comment]
@rwjblue I have added it to my to-do list; wanted to get the issue up 1. before I forgot and 2. so someone else can do the audit if they can get to it before I can.

**Comment by rwjblue** [comment]
I've updated the title to make that clearer. 😄

**Comment by rajasegar** [comment]
I just did a quick grep in the docs/rules folder to find whichever rules don't have the References section, and I found out this:

 - [ ] [attribute-indentation.md](../blob/master/docs/rule/attribute-indentation.md)
 - [ ] [block-indentation.md](../blob/master/docs/rule/block-indentation.md)
 - [ ] [eol-last.md](../blob/master/docs/rule/eol-last.md)
 - [ ] [inline-link-to.md](../blob/master/docs/rule/inline-link-to.md)
 - [ ] [invocable-blacklist.md](../blob/master/docs/rule/invocable-blacklist.md)
 - [ ] [linebreak-style.md](../blob/master/docs/rule/linebreak-style.md)
 - [ ] [modifier-name-case.md](../blob/master/docs/rule/modifier-name-case.md)
 - [ ] [no-attrs-in-components.md](../blob/master/docs/rule/no-attrs-in-components.md)
 - [ ] [no-bare-strings.md](../blob/master/docs/rule/no-bare-strings.md)
 - [ ] [no-duplicate-attributes.md](../blob/master/docs/rule/no-duplicate-attributes.md)
 - [ ] [no-forbidden-elements.md](../blob/master/docs/rule/no-forbidden-elements.md)
 - [ ] [no-html-comments.md](../blob/master/docs/rule/no-html-comments.md)
 - [ ] [no-implicit-this.md](../blob/master/docs/rule/no-implicit-this.md)
 - [ ] [no-inline-styles.md](../blob/master/docs/rule/no-inline-styles.md)
 - [ ] [no-input-block.md](../blob/master/docs/rule/no-input-block.md)
 - [ ] [no-input-tagname.md](../blob/master/docs/rule/no-input-tagname.md)
 - [ ] [no-invalid-block-param-definition.md](../blob/master/docs/rule/no-invalid-block-param-definition.md)
 - [ ] [no-invalid-interactive.md](../blob/master/docs/rule/no-invalid-interactive.md)
 - [ ] [no-log.md](../blob/master/docs/rule/no-log.md)
 - [ ] [no-nested-interactive.md](../blob/master/docs/rule/no-nested-interactive.md)
 - [ ] [no-outlet-outside-routes.md](../blob/master/docs/rule/no-outlet-outside-routes.md)
 - [ ] [no-partial.md](../blob/master/docs/rule/no-partial.md)
 - [ ] [no-quoteless-attributes.md](../blob/master/docs/rule/no-quoteless-attributes.md)
 - [ ] [no-shadowed-elements.md](../blob/master/docs/rule/no-shadowed-elements.md)
 - [ ] [no-trailing-spaces.md](../blob/master/docs/rule/no-trailing-spaces.md)
 - [ ] [no-unbalanced-curlies.md](../blob/master/docs/rule/no-unbalanced-curlies.md)
 - [ ] [no-unbound.md](../blob/master/docs/rule/no-unbound.md)
 - [ ] [no-unnecessary-concat.md](../blob/master/docs/rule/no-unnecessary-concat.md)
 - [ ] [no-unused-block-params.md](../blob/master/docs/rule/no-unused-block-params.md)
 - [ ] [no-yield-block-params-to-else-inverse.md](../blob/master/docs/rule/no-yield-block-params-to-else-inverse.md)
 - [ ] [quotes.md](../blob/master/docs/rule/quotes.md)
 - [ ] [self-closing-void-elements.md](../blob/master/docs/rule/self-closing-void-elements.md)
 - [ ] [simple-unless.md](../blob/master/docs/rule/simple-unless.md)
 - [ ] [table-groups.md](../blob/master/docs/rule/table-groups.md)
 - [ ] [template-length.md](../blob/master/docs/rule/template-length.md)

**Comment by locks** [comment]
Fixed by https://github.com/ember-template-lint/ember-template-lint/pull/1480. The linked PR adds a linting rule which should make sure new rules have a references section.
