### ISSUE TITLE
extract a more convenient .matches type API

### ISSUE THREAD

**Issue by MelSumner** [ember-template-lint/ember-template-lint#1425]
From this code: 

```js
function isMustacheString(node) {
  return (
    node 
    && node.value.type === 'MustacheStatement' 
    && node.value.path.type === 'StringLiteral'
  );
}
```

It became a little more clear that it would be useful to have a `.matches` `.type` API. 

(Issue based on Based on this comment: https://github.com/ember-template-lint/ember-template-lint/pull/1187#discussion_r444957724)

**Comment by rwjblue** [comment]
I would like to have an API that works like this:

```js
match(node, {
  type: 'MustacheStatement',
  value: {
    path: {
      type: 'StringLiteral',
    }
  }
});
```

Specifically, it avoids having to do gnarly boolean operations in each rule...

**Comment by josephdsumner** [comment]
> I would like to have an API that works like this:
> 
> ```js
> match(node, {
>   type: 'MustacheStatement',
>   value: {
>     path: {
>       type: 'StringLiteral',
>     }
>   }
> });
> ```
> 
> Specifically, it avoids having to do gnarly boolean operations in each rule...

I've gotten started on a WIP for this [here](https://github.com/josephdsumner/ember-template-lint/compare/master...josephdsumner:feature/match-api) with the following structure:
- `lib\helpers\node-matcher`
- `NodeMatcher.match(node, ref)`, where `ref` can be a single reference node to match against OR an array of reference nodes. In the latter case, it returns `true` if the node matches any one of the reference nodes contained in that array.

Probably sensible to make the matcher as a pre-requisite to merging 'no-duplicate-id' #1187 , given how much it comes up.

**Comment by Turbo87** [comment]
I assume we can close this, now that #1430 was merged
