### ISSUE TITLE
update print pending feature 

### ISSUE THREAD

**Issue by MelSumner** [ember-template-lint/ember-template-lint#1440]
update the print pending feature to include line and column information for suppression.

we want to prevent further regressions of a given rule in a file when suppression is included in the config file.

**Comment by rwjblue** [comment]
This wouldn't be a breaking change, doesn't need to block 3.0.

**Comment by MelSumner** [comment]
@rwjblue are we deprecating this feature or keeping it?

**Comment by rwjblue** [comment]
We are deprecating the current system, and replacing it with the stuff in #1577. But the thing is, this rule is **specifically** the thing that we are trying to solve.

**Comment by rwjblue** [comment]
Closing in favor of https://github.com/ember-template-lint/ember-template-lint/issues/1557 which is nearly completed.
