### ISSUE TITLE
New Rule Request: `no-hidden-body`

### ISSUE THREAD

**Issue by MelSumner** [ember-template-lint/ember-template-lint#1506]
Requesting a new rule to support [WCAG 4.1.2 - Name, Role, Value (Level A)](https://www.w3.org/TR/WCAG21/#name-role-value) - no-hidden-body. 

The `aria-hidden` attribute should never be present on the `<body>` element, as it hides the entire document from assistive technology.

**Comment by rajasegar** [comment]
I am picking this one , @MelSumner Can you please assign it to me?
