### ISSUE TITLE
New rule request: require-each-key

### ISSUE THREAD

**Issue by EvgenyOrekhov** [ember-template-lint/ember-template-lint#1520]
We were having huge performance issues in our projects when rendering table rows.

In our case, a single change to a single table cell was causing **all rows** to rerender, which was blocking the main thread for up to more than a second.

After an investigation I found out that it was a problem with how we use `{{#each}}`.

After we added [`key`](https://api.emberjs.com/ember/release/classes/Ember.Templates.helpers/methods/each#specifying-keys) to all our `each`es, Ember stopped rerendering all rows, but only the ones that actually needed to be updated.

For example, in one of the cases (selecting a table row via clicking a checkbox) resulted in a 10x performance increase (from ~300 ms down to ~30 ms).

This is applicable not only to tables, but to any usage of `{{#each}}`.

I would like to have a rule that will require to always use `key` with `{{#each}}`.

Examples of **valid** code:

```hbs
{{#each this.items key="id" as |item|}}
  {{item.name}}
{{/each}}
```

```hbs
{{#each this.items key="deeply.nested.id" as |item|}}
  {{item.name}}
{{/each}}
```

```hbs
{{#each this.items key="@index" as |item|}}
  {{item.name}}
{{/each}}
```

```hbs
{{#each this.items key="@identity" as |item|}}
  {{item.name}}
{{/each}}
```

Examples of **invalid** code:

```hbs
{{#each this.items as |item|}}
  {{item.name}}
{{/each}}
```

```hbs
{{#each this.items key="@invalid" as |item|}}
  {{item.name}}
{{/each}}
```

**Comment by EvgenyOrekhov** [comment]
This is especially relevant (and will become more and more relevant) due to the move to working with data in an immutable fashion (as recommended by [Glimmer docs](https://glimmerjs.com/guides/tracked-properties), see "The Immutable Pattern" section). So in most of the cases the default `@identity` key doesn't work, and causes all items to be rerendered.

**Comment by rajasegar** [comment]
@EvgenyOrekhov What do you mean by `key="@invalid"` in the second example of invalid code?

**Comment by EvgenyOrekhov** [comment]
@rajasegar According to the [documentation](https://api.emberjs.com/ember/release/classes/Ember.Templates.helpers/methods/each#specifying-keys), the only valid "special" keys (with the `@` symbol) are `@index` and `@identity`.

**Comment by rajasegar** [comment]
Thanks @EvgenyOrekhov for the clarification
@bmish I can pick this up if it sounds good for a new rule, can you please assign it to me?

**Comment by EvgenyOrekhov** [comment]
Added `key="deeply.nested.id"` example to the issue description.
