### ISSUE TITLE
Warn about curly with property reference and arguments

### ISSUE THREAD

**Issue by Turbo87** [ember-template-lint/ember-template-lint#1563]
I just wrote something like `data-test-foo={{this.foo "foo" "bar"}}` in one of our templates and the console showed:

> Uncaught (in promise) Error: Expected call head to be a string, got [32,0,["foo"]]

My intention was to write `data-test-foo={{if this.foo "foo" "bar"}}`, but for some reason I forgot the `if`. It would be nice if we had a rule that warned about this case, where you have a curly with multiple arguments and the first refers to a property or argument. I haven't been able to come up with a good name for it yet though.

**Comment by rwjblue** [comment]
🤔 the issue is that **very soon** (by some definition) Ember will actually allow that and invoke a helper that was stored at `this.foo`. That is part of [emberjs/rfcs#432](https://github.com/emberjs/rfcs/blob/master/text/0432-contextual-helpers.md).

**Comment by Turbo87** [comment]
yeah... I was afraid of that answer 😅
