### ISSUE TITLE
Invalid rule configuration found: no-forbidden-elements

### ISSUE THREAD

**Issue by sivanarayanan07** [ember-template-lint/ember-template-lint#1593]
Added`no-forbidden-elements': ['img']` in the `.template-lintrc` file but it gives  me a error as ` Invalid rule configuration found: no-forbidden-elements`.

Tried mentioning a boolean value, still got the same error.

is the rule deprecated or is it a bug?

**Comment by bmish** [comment]
I tried the same configuration as you and it worked for me. Are you on the latest ember-template-lint version?

**Comment by sivanarayanan07** [comment]
Updating the version helped me. Thank you @bmish .
