### ISSUE TITLE
Add support for i18n translations file?

### ISSUE THREAD

**Issue by amyrlam** [ember-template-lint/ember-template-lint#160]
If I have `bare-strings` set to true, I don't get applicable rules like `link-rel-noopener` checked in my `translations.js` file. Is this functionality something that could be enabled? 

(Seems like `self-closing-void-elements`, `img-alt-attributes`, maybe others would apply to a translations.js file too.)

If so...I don't know how to add that file to be linted yet, but am interested in working on it.

**Comment by rwjblue** [comment]
Hmm. Right now only template files on disk are being linted (think `*.hbs` files). 

I'm happy to brainstorm on this and figure out a path forward...

**Comment by rwjblue** [comment]
I guess my first question is, what does translations.js contain? Does it contain only templates? If not, how do we know a given translation is a template?

**Comment by amyrlam** [comment]
My `translations.js` file contains things like this:

```
export default {
  account: {
    delete: 'Confirm that you want to delete <strong>{{email}}</strong>',
    coolLink: 'Learn more about <a href="http://www.example.com">stuff here</a>.'
  }
}
```

So in this example, `link-rel-noopener` wouldn't be enforced since it's not in a `hbs`. But none of my links are in a `hbs` if `bare-strings` is true.

Similar translation file here in HospitalRun: https://github.com/HospitalRun/hospitalrun-frontend/blob/master/app/locales/en/translations.js

I'm using ember-i18n.

**Comment by rwjblue** [comment]
Awesome, that's a good example. How do we differentiate translations that are HBS / HTML content?

**Comment by amyrlam** [comment]
Not sure. Also not sure what an answer re: HBS / HTML would mean?

So for my work project (not open source), all of the items in `translations.js` are used in HBS. 

It seems like HospitalRun is the same way, all of the items in `translations.js` are used in HBS. HTML files don't have translations e.g. https://github.com/HospitalRun/hospitalrun-frontend/blob/master/app/index.html#L29

i18n from `translations.js` could be used in a JS file too.

**Comment by rwjblue** [comment]
> i18n from translations.js could be used in a JS file too.

Right, this is what I was talking about.  How can we know that given entries in `translations.js` are intended for template usage or JS usage?  Or maybe it doesn't matter?

**Comment by rwjblue** [comment]
If we assume for the moment that we want to process all of the entries in `translations.js` through the template linter (which might be fine regardless?) the only real blocker here would be to ensure that you could disable the `bare-string`s rule when processing the language specific translations files, right?

**Comment by amyrlam** [comment]
I guess when translations are in a JS file it's really still appearing in a HBS. So...not sure.

What do you mean by this?
> the only real blocker here would be to ensure that you could disable the bare-strings rule when processing the language specific translations files, right?

I'm amyrlam on the Ember Slack if easier to chat there!

**Comment by rwjblue** [comment]
Semi-related to https://github.com/ember-template-lint/ember-template-lint/issues/886

**Comment by amyrlam** [comment]
Stale, closing
