### ISSUE TITLE
TODO feature: when TODOs are resolved, empty folder remains

### ISSUE THREAD

**Issue by MelSumner** [ember-template-lint/ember-template-lint#1684]
Expected: 
Once all issues are resolved and the corresponding .json files have been removed (via the `--update-todo` command), the folder previously containing the todos should be removed. 

Actual: 
The empty folder remains. 

Screenshot (observe the folder starting with 3ca6): 
![image](https://user-images.githubusercontent.com/4587451/104322371-848def80-54aa-11eb-9883-b60a1c57add5.png)

**Comment by scalvert** [comment]
This is intentional. The `.lint-todo` directory is intended to operate similarly to the `.git` directory; it's a hidden storage directory that isn't intended to be viewed by users.

There's a non-trivial amount of i/o involved in creating/deleting directories, and as such we're trying to minimize this i/o as much as possible when managing TODOs. I'd prefer to keep this as is.

Can you articulate why this is a concern for you?

**Comment by scalvert** [comment]
Also I wouldn't label this a bug, as it was intentional.

**Comment by MelSumner** [comment]
This one feels very untidy. I am thinking about it from the perspective of a project's lifetime, there will always be new todos added and existing todos fixed. I think that keeping the empty folders is adding an extra level of complexity for developers that would be unwelcome (will they end up needing to hunt through these folders? Do we anticipate that they would remove them manually? If they will remove them manually why not remove them automatically?).

**Comment by scalvert** [comment]
What complexity? What will they need to hunt for (they shouldn't, as that's a failure on our part)? 

Under what circumstance do you think they should remove them manually?

**Comment by scalvert** [comment]
> This one feels very untidy. I am thinking about it from the perspective of a project's lifetime, there will always be new todos added and existing todos fixed.

I've waffled a bit on this. I agree that over time it could get messy, and that slightly outweighs the extra I/O one could incur by removing/recreating these directories. 

I've made the fix in the todo-utils lib.

**Comment by scalvert** [comment]
Resolved as part of #1688 (by way of the dependency bump of `@ember-template-lint/todo-utils`)
