### ISSUE TITLE
Do not mention future deprecated `{{hasBlock}}` and `{{hasBlockParams}}`

### ISSUE THREAD

**Issue by MrChocolatine** [ember-template-lint/ember-template-lint#1704]
I just read about the recent new rule `no-yield-to-default`:
https://github.com/ember-template-lint/ember-template-lint/blob/44f732506baa5e6b7bc7f44cd060ba81a9b14c31/docs/rule/no-yield-to-default.md

And, to me, we should not mention the helpers `{{hasBlock}}` and `{{hasBlockParams}}` since they are going to be deprecated. Okay it won't happen right now but still, better not to recommended a future deprecated syntax.

https://github.com/ember-template-lint/ember-template-lint/blob/44f732506baa5e6b7bc7f44cd060ba81a9b14c31/docs/rule/no-yield-to-default.md#L24-L50

The RFC **Deprecate {{hasBlock}} and {{hasBlockParams}} in templates**:
https://github.com/emberjs/rfcs/pull/689

**Comment by rwjblue** [comment]
Yes please!!! We should absolutely do this.

Help wanted, this is probably a really good initial rule to write to get your feet wet...

**Comment by rwjblue** [comment]
The new rule should be named `no-deprecated-hasBlock` or something like that.

**Comment by lifeart** [comment]
may be related: https://github.com/ember-template-lint/ember-template-lint/pull/1731

**Comment by scalvert** [comment]
As @lifeart mentioned, #1731 is effectively covering this from the rule side. I also opened #1756 to deal with the original issue in the `no-yield-to-default` [docs](https://github.com/ember-template-lint/ember-template-lint/blob/44f732506baa5e6b7bc7f44cd060ba81a9b14c31/docs/rule/no-yield-to-default.md).
