### ISSUE TITLE
rule request: no-unknown-arguments-for-link-to-component

### ISSUE THREAD

**Issue by lifeart** [ember-template-lint/ember-template-lint#1730]
ref: https://discord.com/channels/480462759797063690/608346628163633192/806564429315047425

Instead of scaring person who have typo in builtin component's arguments, we have to higlight issue, to improve overall DX and help to find tricky bugs, related to routing component params. 

tldr:

common typos `@rote, @rout, @routes` should be higlighter (basically, easy to higlight all `unknown` arguments) in `<LinkTo >` component.

**Comment by rwjblue** [comment]
Ya, definitely a good idea. The list of known good arguments is in https://github.com/emberjs/rfcs/blob/master/text/0707-modernize-built-in-components-2.md#summary.

**Comment by lifeart** [comment]
draft: https://github.com/ember-template-lint/ember-template-lint/pull/1734
