### ISSUE TITLE
rule request: no-capital-arguments

### ISSUE THREAD

**Issue by lifeart** [ember-template-lint/ember-template-lint#1732]
Ref: https://discord.com/channels/480462759797063690/483601670685720591/806661156936482876

https://github.com/emberjs/rfcs/blob/68812bf2d439c6bb77ad491e0159b371b68c5c35/text/0276-named-args.md#reserved-names

![5262824E-7B8F-4D8E-8229-D4B96BC7E362](https://user-images.githubusercontent.com/1360552/106854582-a0ad3700-66cc-11eb-967b-362a88786c13.jpeg)

tldr: @Foo, not working, and emitting reserved word error

`{{#let @NavItem as |NavItem|}}` results in the template compiler saying `Assertion Failed: '@NavItem' is reserved.` but `{{#let this.args.NavItem as |NavItem|}}` works

cc @locks

**Comment by rwjblue** [comment]
Ya this is a good idea, though I **do** think we should relax that rule on the Ember side.

**Comment by rwjblue** [comment]
We discussed this in a recent Ember core team meeting, and we are going to relax this restriction.

**Comment by lifeart** [comment]
@rwjblue I'm wondering, could we lend rule asap (because it's not working in current embers), and later we could disable it (once changes landed), also, it's good case for https://github.com/ember-template-lint/ember-template-lint/issues/1741
