### ISSUE TITLE
Feature request: rule for consistent naming of named-blocks

### ISSUE THREAD

**Issue by boris-petrov** [ember-template-lint/ember-template-lint#1772]
I'm not sure what Ember's convention is on named-block naming (`<:foo-bar>` vs `<:fooBar>`) but a rule to force the "right" one would be nice.

**Comment by rwjblue** [comment]
Ya, I agree. I think it doesn't _really_ matter what folks choose, but it would be nice to be able to enforce consistency.

I think `require-valid-named-block-naming-format` as a rule name seems good. We could then have options for "PascalCase", "camelCase", and "dasher-ized".

Once we land it, we could add it to the stylistic rule set (IMHO the PascalCase looks the best).

**Comment by scalvert** [comment]
I agree. I think the default should be PascalCase?

**Comment by rwjblue** [comment]
ya, I think so

**Comment by boris-petrov** [comment]
Note that there is also a `<:default>` (which I believe can't be changed) so perhaps `camelCase` is better for consistency?

**Comment by rwjblue** [comment]
FWIW, I suspect that `:default` will be a bit uncommon (most things that _use_ a default only should just not pass a named block, and having a `:default` + some other named block is fairly confusing). But we can explicitly allow `default` as an exception.

**Comment by bertdeblock** [comment]
Note that, [named blocks must start with a lower case letter](https://github.com/glimmerjs/glimmer-vm/blob/3874a63ce863f94078d93d22cba66dbb23c496d3/packages/%40glimmer/integration-tests/test/syntax/named-blocks-test.ts#L74-L83). So PascalCase is out of the question it seems.
