### ISSUE TITLE
no-bare-strings should check placeholder attribute on built-in Input components

### ISSUE THREAD

**Issue by jaydgruber** [ember-template-lint/ember-template-lint#1800]
The default config of `no-bare-strings` checks `placeholder` on an `<input>` element.
It should also check `placeholder` for `<Input>` and `<Textarea>` built-in components.
ref: https://api.emberjs.com/ember/release/classes/Ember.Templates.components/methods/Input?anchor=Input

**Comment by rwjblue** [comment]
@jaydgruber - Totally agreed!
