### ISSUE TITLE
Add `no-deprecated-with` rule

### ISSUE THREAD

**Issue by rwjblue** [ember-template-lint/ember-template-lint#1808]
Based on https://github.com/emberjs/rfcs/blob/master/text/0445-deprecate-with.md, we should add a rule to prevent usage of `{{#with`.

**Comment by bertdeblock** [comment]
@rwjblue Can you assign this one to me please? Seems like a reasonable one to do to got the know the project.

**Comment by rwjblue** [comment]
@bertdeblock - Yep, sounds great!

This might be a nice example rule to crib from:

https://github.com/ember-template-lint/ember-template-lint/blob/master/lib/rules/inline-link-to.js
https://github.com/ember-template-lint/ember-template-lint/blob/master/test/unit/rules/inline-link-to-test.js

I think we can also include a fixer if you are up for it, though I'm happy to land the rule itself separately from the fixer...

**Comment by bertdeblock** [comment]
@rwjblue Cool, thanks!

Would the fix logic look something like this?
- If invoked with a sub expression (e.g. `(hash ...)` or `(array ...)`) transform to a simple let block
- If invoked with a path expression (e.g. `@model.blogPosts`) transform to a let-if block
- If invoked with an inverse block transform to a let-if-else block

I've also noticed that the following scenario's work and was wondering if these should be taken into account somehow:
- It's possible to invoke `{{#with` with multiple block params (the fix could just use the first one and omit the others?)
- It's possible to invoke `{{#with` without any block params, basically it just seems to work like an `{{#if` block then (the fix could be to replace it with a normal `{{#if` block?)
