### ISSUE TITLE
role="switch" cause no-invalid-role error

### ISSUE THREAD

**Issue by jkoksharova** [ember-template-lint/ember-template-lint#1818]
https://github.com/ember-template-lint/ember-template-lint/blob/8085aa967a60f7365627dcd074b60517e803ff31/lib/rules/no-invalid-role.js#L162

Per https://www.w3.org/WAI/PF/aria/roles#widget_roles switch role is valid one however it cause an error with v3 ember-lint-template as it's not in the list of valid roles. Looks like a defect.

**Comment by rwjblue** [comment]
Yep, definitely seems like a bug. 

@jkoksharova - Think you might have some time to send in a PR to fix? I think we'd need to add it to the list you linked, and add a new test to this `good` example list:

https://github.com/ember-template-lint/ember-template-lint/blob/8085aa967a60f7365627dcd074b60517e803ff31/test/unit/rules/no-invalid-role-test.js#L13-L36

**Comment by Windvis** [comment]
@rwjblue I took a look at this and it seems there are more roles missing. I cross referenced with the [documentation](https://www.w3.org/TR/wai-aria/#widget_roles) and it seems the following aren't listed in the `VALID_ROLES` set.

- searchbox
- switch
- cell
- feed
- figure
- table
- term

Should these be added as well? Or is there a reason why they weren't added before.

**Comment by Windvis** [comment]
And should each valid role have at least 1 test case as well?
