### ISSUE TITLE
no-duplicate-landmark-elements shows error for roles "presentation" and "none" on images

### ISSUE THREAD

**Issue by sebastianhelbig** [ember-template-lint/ember-template-lint#1819]
Multiple different images (`<img … />`) on the same page with `role="presentation"` or `role="none"` trigger the error:

`If multiple landmark elements (or elements with an equivalent role) of the same type are found on a page, they must each have a unique label.  no-duplicate-landmark-elements`

This error should not be shown, as using `role="presentation"` and `role="none"` mutiple times (for images) is perfectly valid.

**Comment by rwjblue** [comment]
That rule isn't intending to look at non-landmark roles at all, this definitely seems like a bug to me.

Thank you for reporting! We'll get it fixed up!
