### ISSUE TITLE
Suggestions in no-unknown-built-in-component-arguments are often a bit misleading

### ISSUE THREAD

**Issue by rwjblue** [ember-template-lint/ember-template-lint#1821]
Some errors from https://github.com/ember-template-lint/ember-template-lint/issues/1820, specifically the "did you mean" text for these is pretty wild to me:

**Input**
```
error  "@autocomplete" is unknown argument for <Input /> component. Did you mean "@value"?  no-unknown-arguments-for-builtin-components
error  "@class" is unknown argument for <Input /> component. Did you mean "@escape-press"?  no-unknown-arguments-for-builtin-components
error  "@required" is unknown argument for <Input /> component. Did you mean "@escape-press"?  no-unknown-arguments-for-builtin-components
error  "@spellcheck" is unknown argument for <Input /> component. Did you mean "@checked"?  no-unknown-arguments-for-builtin-components
```

**LinkTo**
```
error  "@class" is unknown argument for <LinkTo /> component. Did you mean "@activeClass"?  no-unknown-arguments-for-builtin-components
error  "@invokeAction" is unknown argument for <LinkTo /> component. Did you mean "@activeClass"?  no-unknown-arguments-for-builtin-components
```

---

I'd like to:

* Teach the rule about all known arguments to the built-ins (even the deprecated ones), and for the deprecated ones either don't provide a suggestion per-se or suggest moving to the attribute
* Determine how we can tell the likelihood that our match is reasonable (`@invokeAction` -> `@activeClass` for example doesn't seem reasonable), and optionally not emit suggestion text if the match isn't confident enough.

**Comment by rwjblue** [comment]
@lifeart - What do you think?

**Comment by lifeart** [comment]
Lol, in my idea `Did you mean...` should handle typos, agree we should add knowledge about deprecated properties and extend messaging | add autofix for this case.
