### ISSUE TITLE
{{#each}} without params?

### ISSUE THREAD

**Issue by reidab** [ember-template-lint/ember-template-lint#185]
This is probably an edge case that may not be worth tackling, but I thought I'd throw it in just in case. I'm running into a situation where `deprecated-each-syntax` and `unused-block-params` seem to be at odds. I have an each block where I'm rendering something once for each item in a collection, but not referencing the items in the collection at all:

```handlebars
{{#each things}}
  <li>foo</li>
{{/each}}
```

This trips the `deprecated-each-syntax` rule, despite not using the `each x in things` syntax. Adding a throwaway block param (`{{#each things as |thing|}}`) trips the `unused-block-params` rules.

I see in [the rule](https://github.com/rwjblue/ember-template-lint/blob/master/lib/rules/deprecations/lint-deprecated-each-syntax.js#L57) that there's a case for this, presumably targeting an even older deprecated `{{#each}}` usage.

**Comment by rwjblue** [comment]
Yeah, in Ember 1.x,  using the following:

```hbs
{{#each things}}
  {{name}}
{{/each}}
```

Would actually grab `name` from each of the entries in `things`. In other words `{{#each foos}}` actually shifted the template context for the block to be a given item in the array being iterated over.

**Comment by rwjblue** [comment]
You are trying to emit a static template block for each item in the array?

**Comment by reidab** [comment]
My actual usage is with the `repeat` helper out of `ember-composable-helpers`, per their examples: https://github.com/DockYard/ember-composable-helpers#repeat

**Comment by bardzusny** [comment]
I recently stumbled upon the very same issue - `{{#each}}` without params has real use-cases, (i.e. just rendering something X times).

OTOH, this rule can just be safely turned off for Ember 2.x altogether - due to `each in ...` syntax being removed from 2.0 altogether. Do you think that would make a good case for removing `deprecated-each-syntax` rule from [`recommended` config](https://github.com/rwjblue/ember-template-lint/blob/master/lib/config/recommended.js#L10) (being applicable only to old 1.x)?

**Comment by rwjblue** [comment]
Ya, I'm game for that...

**Comment by rwjblue** [comment]
Addressed by #188

**Comment by GavinJoyce** [comment]
https://github.com/ember-template-lint/ember-template-lint/releases/tag/v3.0.0 seems to have enabled `deprecated-each-syntax` in "recommended". I'm hitting the same issue as above using:

```hbs
{{#each (repeat 3)}}
  ...
{{/each}}
```

I'll disable the rule locally, but I wonder if this rule should belong in recommended?

**Comment by rwjblue** [comment]
🤦 yeah I forgot all about this

**Comment by rwjblue** [comment]
I'd like to update `deprecated-each-syntax` to avoid issuing a deprecation when `{{this}}` is not used within the block.
