### ISSUE TITLE
Request: separate out fixable functionality and removing stale todos from `--fix` flag

### ISSUE THREAD

**Issue by MelSumner** [ember-template-lint/ember-template-lint#1852]
## Summary 
It's confusing that the `--fix` flag will remove todos that have been resolved AND ALSO fix issues that are auto-fixable. A different command should be used to remove resolved todos.

## Details 
Scenario: A developer is working on their part of a large project. They are only responsible for folder `app/foo/` which had an a11y-related todo. 

Developer fixes the issue and then runs `yarn lint:hbs --fix` to remove the todo. 

Developer sees that the command resulted in these changes:
- the correct todo file was removed (related to file changes in the `app/foo/` folder
- auto-fixable issues in `app/bar/` folder were also completed (oh no!)

This adds an extra step to the developer workflow. The command that was intended to quickly and easily remove the todo has now made more work for them- they have to undo the changes they unintentionally made. 

It's also more tedious to try to run the `--fix` command specifically on the file where the issue was resolved. 

Then intention of the `--fix` to remove the todo was ease of use, and right now it's not meeting that criteria.

**Comment by scalvert** [comment]
I can see this being a problem based on the use case you described. We wanted the `--fix` flag to remove todos to simplify the workflow, but if it's have the opposite effect I'm totally open to changing this.

**Comment by Techn1x** [comment]
I'd really like this feature too. I have outlined some justifications in one of the comments for https://github.com/ember-template-lint/ember-template-lint/issues/1898

**Comment by MelSumner** [comment]
We discussed this today and we're going to add a `--prune-todo` flag that will remove any invalid/fixed/expired todos. We'll update the message to instruct users to run this flag instead. 

Related #1873 #1905

**Comment by MelSumner** [comment]
The flag ended up being `--clean-todo` and it's in version 3.4.0, now available. Closing issue.
