### ISSUE TITLE
New rule: `forbidden-components`

### ISSUE THREAD

**Issue by Turbo87** [ember-template-lint/ember-template-lint#1869]
We use an addon internally to shared components between several apps and we're looking for a better way to deprecate components. Using `Ember.deprecate()` causes warnings and noise in the test suite, which we'd prefer to avoid because it does not scale well (as in: our CI logs grow to dozens of MB due to all the warnings).

My idea would be a new rule: `forbidden-components` that is user-configurable with a set of component names that are disallowed.

### Open Questions

- I realize that `forbidden-components` does not match our regular naming policy, but `no-components` sounds too much like *all* components are forbidden by this rule. I'm open to better naming suggestions

- I also see that this could potentially conflict with any upcoming template import designs, but until that lands this rule could still be beneficial.

- Ideally we could switch between `error` and `warnings` for the individual component names, but that seems somewhat hard to implement in the current structure, so I guess just having one global error level will have to be sufficient for now.

**Comment by bmish** [comment]
Is our existing rule [no-restricted-invocations](https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/no-restricted-invocations.md) what you want?

**Comment by Turbo87** [comment]
lol :D 

yep, that is exactly what I want. I just didn't find it in the list apparently 😂

**Comment by jakebixbyavalara** [comment]
@Turbo87 We just implemented this rule ourselves, the config threw me at first, we're using an array of objects that contains the name of the component with the message for it.
```
   'no-restricted-invocations': [
          { names: ['component-one'], message: 'Please use `component-three` instead' },
          { names: ['modal-dialog', 'custom-modal'], message: "Please use the `new-modal` component instead' }
        ],
```
