### ISSUE TITLE
configure link-rel to validate both noopener and noreferrer

### ISSUE THREAD

**Issue by ingride** [ember-template-lint/ember-template-lint#187]
Firefox [does not currently support "noopener"](https://bugzilla.mozilla.org/show_bug.cgi?id=1222516) and this will be addressed on version 52, that will be released end of March '17.  

To prevent this [vulnerability](https://www.jitbit.com/alexblog/256-targetblank---the-most-underestimated-vulnerability-ever/), best practice would be to validate both `noopener` and `noreferrer` .

From a conversation with @rwjblue we have decided to make this rule configurable to be able to validate `both` while maintaining the backward compatibility and allow current users to address this at their own pace.

**Comment by rwjblue** [comment]
👋 @ingride 😃 

I think this is done now (and the recommended config uses the newer `strict` config by default)
