### ISSUE TITLE
Max line length rule

### ISSUE THREAD

**Issue by dfenske** [ember-template-lint/ember-template-lint#1884]
Is there a rule that can enforce a max line length in HBS files? Seems like some incorporate that as part of their rule, but none that does just that alone.

**Comment by bmish** [comment]
We do have a related, optional rule [template-length](https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/template-length.md). I suppose we could add a `line-length` rule too. But I think the longer-term vision is that [ember-template-lint-plugin-prettier](https://github.com/ember-template-lint/ember-template-lint-plugin-prettier) would control most styling like this.
