### ISSUE TITLE
require-valid-alt-text incorrectly parsing alt

### ISSUE THREAD

**Issue by Techn1x** [ember-template-lint/ember-template-lint#1896]
`<img alt="logout" ... />` fails the `require-valid-alt-text` rule, likely because the word logout contains the word "logo" (which is a banned term).

We may want to do a more comprehensive test here than just an 'includes'
https://github.com/ember-template-lint/ember-template-lint/blob/62589045e5ed5c6ca14eed13e80f563f30fb8520/lib/rules/require-valid-alt-text.js#L146-L148

I could see this causing issues for other _valid_ alt text entries. For example `alt="my photography class"` would fail due to the word `photo` being present in the string

examples of other words in alt text that would cause this lint issue
photography
telephoto
analogous
logon
logout
pilgrimage
photon

**Comment by bertdeblock** [comment]
Maybe the solution could be as simple as: `normalizedAltValue.split(' ').includes(word)`? Haven't tested this myself against the current tests though.
