### ISSUE TITLE
Can I --fix just the manually fixed todos?

### ISSUE THREAD

**Issue by Techn1x** [ember-template-lint/ember-template-lint#1898]
I can't quite gather from the docs if what I am doing is expected behaviour or a bug.

I am working on an app that has hundreds of template lint violations, so I have marked them all as todo. We're not yet ready to deal with mass autofixing these and the merge conflicts that might cause.

I recently manually fixed 3 violations, and now my linting command does this;

```bash
~/my-app/ $ yarn ember-template-lint .
yarn run v1.22.10
$ /home/user/my-app/node_modules/.bin/ember-template-lint .
app/manage/certificates/template.hbs
  -:-  error  Todo violation passes `no-positional-data-test-selectors` rule. Please run `--fix` to remove this todo from the todo list.  invalid-todo-violation-rule
  -:-  error  Todo violation passes `no-implicit-this` rule. Please run `--fix` to remove this todo from the todo list.  invalid-todo-violation-rule
  -:-  error  Todo violation passes `no-implicit-this` rule. Please run `--fix` to remove this todo from the todo list.  invalid-todo-violation-rule

✖ 3 problems (3 errors, 0 warnings)
  3 errors and 0 warnings potentially fixable with the `--fix` option.
error Command failed with exit code 1.
```

Awesome! I see what you're going for there. Now I need to remove those from the todo list (just like how pending worked before). So then I run the `--fix` flag as it says, to do just that.

But it seems it *autofixes my whole project* with codemods instead of just removing those 3 completed todo items, and it seems it deletes a bunch of my .lint-todos as well, bringing old errors back?

```bash
~/my-app/ $ yarn ember-template-lint . --fix
yarn run v1.22.10
$ /home/user/my-app/node_modules/.bin/ember-template-lint . --fix
app/manage/template.hbs
  8:70  error  Do not use `action` as {{action ...}}. Instead, use the `on` modifier and `fn` helper.  no-action
  22:0  error  You are using the component {{flash-messages}} with curly component syntax. You should use <FlashMessages> instead. If it is actually a helper you must manually add it to the 'no-curly-component-invocation' rule configuration, e.g. `'no-curly-component-invocation': { allow: ['flash-messages'] }`.  no-curly-component-invocation
  2:87  error  Ambiguous path 'isShowingCleverModal' is not allowed. Use '@isShowingCleverModal' if it is a named argument or 'this.isShowingCleverModal' if it is a property on 'this'. If it is a helper or component that has no arguments, you must either convert it to an angle bracket invocation or manually add it to the 'no-implicit-this' rule configuration, e.g. 'no-implicit-this': { allow: ['isShowingCleverModal'] }.  no-implicit-this
  22:2  error  Ambiguous path 'flash-messages' is not allowed. Use '@flash-messages' if it is a named argument or 'this.flash-messages' if it is a property on 'this'. If it is a helper or component that has no arguments, you must either convert it to an angle bracket invocation or manually add it to the 'no-implicit-this' rule configuration, e.g. 'no-implicit-this': { allow: ['flash-messages'] }.  no-implicit-this
  8:63  error  Event handler methods like `click` should not be passed in as a component arguments  no-passed-in-event-handlers

app/components/add-teachers-dialog/template.hbs
  6:101  error  Do not use `action` as {{action ...}}. Instead, use the `on` modifier and `fn` helper.  no-action
  10:106  error  Do not use `action` as {{action ...}}. Instead, use the `on` modifier and `fn` helper.  no-action

... + heaps of old errors that I had previously marked as todo
```

Is this what is supposed to happen? Or is it a bug? It _kind of_ matches what was mentioned in this issue, where the OP also said `--fix` just autofixes everything https://github.com/ember-template-lint/ember-template-lint/issues/1887

**Comment by Techn1x** [comment]
Oh wow, looks like there's some recent movement on improving this here https://github.com/ember-template-lint/ember-template-lint/pull/1895

Though I am not sure if that'll fix the problem entirely..

**Comment by MelSumner** [comment]
We believe that `--fix` is safe to run on your app (and should be considered part of app maintenance). 

However, if you wanted to just run fix for the file you fixed, then run `ember-template-lint app/manage/certificates/template.hbs --fix` and that should only run the fix flag for that specific file.

**Comment by Techn1x** [comment]
I don't doubt it's safe to run. I just don't want to run it yet. 

Running it only on a single file is better, but not quite there.

There's plenty of reasons not to run autofix/codemods even though they are safe to run.
- it often destroys template formatting (specifically when going from curly components to angle brackets)
- increases chance of merge conflicts
- makes PR diffs a lot harder to read. Maybe I would like to run the autofixes in a follow up PR to my feature PR, for example.
- if needing to hotfix one line for a prod deploy. Can't have the template linter forcing me to autofix the entire file to get that one change out.

> --fix is safe to run on your app (and should be considered part of app maintenance)

My understanding of the point of todos is to defer this app maintenance in a safe way, keeping rules enabled to detect & prevent new occurrences, until the dev team is ready to deal with the existing lint violations.

I find this todos feature a little useless without the ability to cross off resolved todo items without causing side effects. Without that it seems a step backwards from the (now deprecated) pending implementation, admittedly pending had less granularity (per-file) but at least it didn't force unrelated code changes when you cross an item off, and you could manually cross those items off the list.

For now I'm going to switch back to warnings or pending. I really like what the todos feature is aiming be but it's not quite there yet. A `--fix-resolved-todos` would be perfect

**Comment by Techn1x** [comment]
I don't mean to sound demanding here. This addon is great 💯 , I'm just a little let down by this one omission

Happy for this to be closed if it's a "wontfix"

**Comment by Techn1x** [comment]
I see you're way ahead of me here. Closing in favour of pre-existing issue https://github.com/ember-template-lint/ember-template-lint/issues/1852
