### ISSUE TITLE
Bug: Todo file isn't being marked as stale if file is moved or deleted

### ISSUE THREAD

**Issue by MelSumner** [ember-template-lint/ember-template-lint#1969]
An issue came to light today where if a file has been moved or removed, but has an associated todo, `yarn lint:hbs` won't find an error (invalid-violation), or remove the associated todo file with `yarn lint:hbs --clean-todo` or `yarn lint:hbs --fix`. 

I also tried this with the explicit path to file - `yarn ember-template-lint path/to/file.hbs` (passes because the file isn't there); `yarn ember-template-lint path/to/file.hbs --clean-todo` (doesn't remove the stale todo file). 

More context (from dupe issue): 
Currently, when processing files for `--clean-todo`, we iterate and operate on individual files. Due to this, we potentially orphan todo files that are no longer valid simply because we don't operate on them.

Examples:

Operating on all files:

```shell
ember-template-lint . --clean-todo
```

will operate on all files, but only those that exist in the directory at that point in time (which will exclude specific files that have been deleted). This will naturally exclude processing of todos that don't have an associated source file.

Operating on specific files

```shell
ember-template-lint app/templates/application.hbs --clean-todo
```

will operate only on that single file, obviously not operating on any files not in this list.

Steps to reproduce:

- create a template with an error
- generate todo for template
- delete template
- run `--clean-todo` or `--update-todo` against your whole working dir and expect that todo file is deleted

Currently, the todo file will not be deleted (as again, we only operate on single files).

**Comment by MelSumner** [comment]
@scalvert do you think this issue would go in todo-utils?

**Comment by scalvert** [comment]
It's probably fine here since it's user facing.

**Comment by scalvert** [comment]
I think this bug refers to the old todo system, using single files per todo, and also pre-autoclean. This isn't an issue with the new system since it operates on single files.
