### ISSUE TITLE
Treat the menuitem as an interactive tag

### ISSUE THREAD

**Issue by joankaradimov** [ember-template-lint/ember-template-lint#197]
Add `menuitem` to `INTERACTIVE_TAG_NAMES`. Although an experimental feature, it is already working in Firefox. There also appears to be some [recent activity](https://bugs.chromium.org/p/chromium/issues/detail?id=412945) in the Chromium bug tracker.

**Comment by MelSumner** [comment]
'menuitem' is a deprecated HTML element, so this issue could be closed.
