### ISSUE TITLE
RULE: Support enforcement of single or double quotes around non-bound values

### ISSUE THREAD

**Issue by notmessenger** [ember-template-lint/ember-template-lint#204]
Make it configurable as to whether single or double quotes should be used in all template syntax (e.g. attributes, property values, closure actions, etc) for non-bound values.

**Comment by rwjblue** [comment]
Totally agreed! Work was started in https://github.com/rwjblue/ember-template-lint/pull/42, but that effort got stalled.  

Would love for someone to pick things back up again...

**Comment by rwjblue** [comment]
I believe this is implemented now: https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/quotes.md
