### ISSUE TITLE
no-duplicate-landmark-elements ignores conditions

### ISSUE THREAD

**Issue by thiagofesta** [ember-template-lint/ember-template-lint#2050]
If a template is wrapped with an `if` statement, this rule still throws when it shouldn't.

Example:
```
{{#if this.showFullFooter}}
  <footer>Full Footer</footer>
{{else}}
  <footer>Compact Footer</footer>
{{/if}}
```

**Comment by bertdeblock** [comment]
Duplicate of https://github.com/ember-template-lint/ember-template-lint/issues/1799.
