### ISSUE TITLE
Can I disallow the Handlebars comment instructions ? 

### ISSUE THREAD

**Issue by thamsrang** [ember-template-lint/ember-template-lint#2106]
I want rule to be in one place **.template-lintrc.js**.
How can disallow the **[Handlebars comment instructions]**(https://github.com/ember-template-lint/ember-template-lint/pull/134) ?

Any arguments available to disable this feature ?

**Comment by dcyriller** [comment]
hmm should you remove the Handlebars comments from your templates?

**Comment by bertdeblock** [comment]
I don't think there's an option to actually **disallow** the usage of `{{! template-lint-disable }}` comments.

**Comment by thamsrang** [comment]
> hmm I'm sure to understand - is it not possible to remove the Handlebars comments from your templates?

I want disabling lint errors to be in one place `.template-lintrc.js`. Then it will easy to track the disabled errors in pending list `.template-lintrc.js`.
If they mention `{{! template-lint-disable }}` to disable an error, then linter should not consider this.
This is to force dev to don't disable error in .hbs files.

**Comment by bertdeblock** [comment]
Do you want to disable the rules because you don't need / like them or because you want to create some sort of TODO overview in one place? There's also the TODO functionality you can use if you want => https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/todos.md

**Comment by thamsrang** [comment]
Thanks @bertdeblock. I will check.

**Comment by MelSumner** [comment]
@bertdeblock I think that @thamsrang wants to prevent use of `{{! template-lint-disable }}`. 

@thamsrang the answer is no, you can't currently do it with the default rule set. See: https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/no-html-comments.md which specifically allows comments in `hbs` files.

You could request a new rule, or write a custom rule in your own codebase that would explicitly check for this kind of comment.
