### ISSUE TITLE
Should we remove `no-whitespace-for-layout` and `no-whitespace-within-word` from the `stylistic` config?

### ISSUE THREAD

**Issue by dcyriller** [ember-template-lint/ember-template-lint#2183]
I wonder if we should not remove these two rules from the `stylistic` config. Indeed, the `stylistic` config gathers rules useful to define a code style. But it seems to me that the two rules are more a matter of how a css style is applied to a template rather than a matter of code style?

For reference:
https://github.com/ember-template-lint/ember-template-lint/blob/5123cbf9f9bdc94319d3110c377a64e402221a9f/lib/config/stylistic.js#L12-L13

**Comment by bmish** [comment]
That's a fair point. Then shouldn't we add them to the `recommended` config since they have a functional impact? Not just affecting code style.

**Comment by dcyriller** [comment]
I am closing the issue as it is resolved on the `next` branch.
