### ISSUE TITLE
Expose infrastructure for testing custom rules.

### ISSUE THREAD

**Issue by rwjblue** [ember-template-lint/ember-template-lint#227]

**Comment by bmish** [comment]
Just to confirm, no progress has been made on this issue, and the issue is referring to "Expose public API's for our custom testing harness" (from https://github.com/ember-template-lint/ember-template-lint/issues/136) for plugins to use, correct?

**Comment by rwjblue** [comment]
Yes, exactly.

**Comment by gabrielcsapo** [comment]
Is there any movement on this front? I wrote a couple custom rules for a project and wanted to know how to test them.

**Comment by gabrielcsapo** [comment]
👋 I might have gotten somewhere. I frankensteined the harnesses in this repo to come up with something like this.

```js
'use strict';

const QUnit = require('qunit');
const _precompile = require('@glimmer/compiler').precompile;

const Linter = require('ember-template-lint')
const LintOrphanedTDefs = require('../../../template-lint-rules/lint-lint-something');

function precompileTemplate(template, ast) {
  _precompile(template, {
    rawSource: template,
    moduleName: 'layout.hbs',
    plugins: {
      ast: ast,
    },
  });
}

function plugin(Rule, name, config) {
  let plugin = new Rule({
    name,
    config
  });

  return env => {
    plugin.templateEnvironmentData = env;

    let visitor = plugin.getVisitor();

    return {
      name,
      visitor
    };
  };
}

QUnit.module('lint-something ', () => {
 assert.expect(1);

    const logs = [];

    class TestRule extends LintSomething {
      log(result) {
        logs.push(result);
      }
    }

    precompileTemplate(`{{t "foo"}}`, [plugin(TestRule, 'lint-something', {})]);

    assert.deepEqual(logs, [{
      message: 'You are linting something',
      line: 1,
      column: 0,
      source: '{{t "foo"}}'
    }])
});
```

**Comment by gabrielcsapo** [comment]
@rwjblue would it make sense to compile this into a helper function people can use?

**Comment by rwjblue** [comment]
Sorry for the delay here @gabrielcsapo. This issue is for exposing the testing system that ember-template-lint itself uses to rule authors.

The main thing to expose (likely from the root `ember-template-lint` module) is this:

https://github.com/ember-template-lint/ember-template-lint/blob/master/test/helpers/rule-test-harness.js

Then folks can write their own test suites like:

https://github.com/ember-template-lint/ember-template-lint/blob/master/test/unit/rules/lint-eol-last-test.js

**Comment by gabrielcsapo** [comment]
It looks like the only thing that needs to be altered to allow this rule-test-harness to work with other frameworks is decoupling the mocha prescribed globals. I will work on getting this up in PR form and altering the docs after the decided solution gets a 👍
