### ISSUE TITLE
Automatically exclude all helpers from `no-curly-component-invocation`

### ISSUE THREAD

**Issue by shankarsridhar** [ember-template-lint/ember-template-lint#2286]
Hey folks, thanks for this wonderful add-on.
I would like to know if there is a way to make this add-on automatically exclude all helpers in the app so that its not needed to manually add the helpers in the app code in the configuration file(.template-lintrc.js, for example).

That is, 
Current way of doing (manual):
```js
rules: {
    'no-curly-component-invocation': {
      allow: ['my-helper', 'my-other-helper'],
    },
  },
```

What I would like to have/proposing
```js
rules: {
// config not needed in this case, since all the exclusions are for helpers 
// which are automatically excluded for the rule 'no-curly-component-invocation'
  },
```

I am using version `3.15.0` of this add-on

**Comment by lifeart** [comment]
Hi @shankarsridhar, not, it's not really possible with current state of things,  but, you could use snippet:

```js
var componentLikeHelpers = Object.keys(require.entries)
    .filter(name=>(name.includes('/helpers/')|| name.includes('/helper')))
    .filter(name=>!name.includes('/-')).map(name=>{
        let path = name.split('/helpers/');
        return path.pop();
    }).filter(name=>!name.includes('/')).uniq();

console.log(JSON.stringify(componentLikeHelpers))
```

to collect all app helpers

**Comment by bmish** [comment]
Maybe the rule doc could be updated to link to this "skipping helpers" part of the codemod doc in case people want to use it for the lint rule too: https://github.com/ember-codemods/ember-angle-brackets-codemod#skipping-helpers
