### ISSUE TITLE
v4 Migration suggests esm conversion is only required for rare cases, but a default config errors without importing any rules directly

### ISSUE THREAD

**Issue by runspired** [ember-template-lint/ember-template-lint#2320]
Offending plugin appears to be ember-template-lint-plugin-prettier

```
(node:76359) UnhandledPromiseRejectionWarning: Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/runspired/github/private/fnb/frontend/node_modules/ember-template-lint/lib/index.js
require() of ES modules is not supported.
require() of /Users/runspired/github/private/fnb/frontend/node_modules/ember-template-lint/lib/index.js from /Users/runspired/github/private/fnb/frontend/node_modules/ember-template-lint-plugin-prettier/lib/rules/prettier.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/runspired/github/private/fnb/frontend/node_modules/ember-template-lint/package.json.
```

**Comment by bmish** [comment]
This should be fixed once @dcyriller releases a new version of ember-template-lint-plugin-prettier containing this change: https://github.com/ember-template-lint/ember-template-lint-plugin-prettier/pull/191

It is true that plugins will need to convert to ESM to support ember-template-lint v4. The [v4 migration guide](https://github.com/ember-template-lint/ember-template-lint/blob/v4.0.0/docs/migration/v4.md) was referring to `.template-lintrc.js` config files not needing to be converted to ESM.

**Comment by dcyriller** [comment]
I have released a v4 of ember-template-lint-plugin-prettier. This issue should be resolved by now!
