### ISSUE TITLE
Executable flag '--version' does not echo correct version

### ISSUE THREAD

**Issue by cvarrick** [ember-template-lint/ember-template-lint#2431]
Installed latest version locally via npm.

Expecting '4.3.0', but output is '0.0.1'.

```
$ node -v
v16.13.0

$ npm -v
8.5.5

$ npm i --save-dev  ember-template-lint@latest

$ npm list ember-template-lint
└── ember-template-lint@4.3.0

$ ./node_modules/ember-template-lint/bin/ember-template-lint.js  --version
0.0.1
```

When installed globally, output is 'unknown'

```
$ npm i -g  ember-template-lint@latest
$ ember-template-lint --version
unknown
```

**Comment by cvarrick** [comment]
It seems that when installed locally, yargs.version() is outputting the version of my module, not ember-template-lint.

**Comment by jamescdavis** [comment]
This is an issue with `yargs`: https://github.com/yargs/yargs/issues/2122
