### ISSUE TITLE
Issues with todos when upgrading from v3.4.2 to v4.3.0

### ISSUE THREAD

**Issue by adc-mhaugen** [ember-template-lint/ember-template-lint#2432]
I'm having trouble upgrading ember-template-lint from `v3.4.2` to `v4.3.0`.  The steps I have taken are:

1. Upgrade from `^3.4.2` to `^4.3.0`.
2. Change my `.template-lintrc.js#extends` property to `['recommended']`.

At this point I run `yarn lint` and it says: "Found .lint-todo directory.  Please run `npx @lint-todo/migrator` to convert to the new todo file format".  So I run that command and it very quickly flashes a message that I need to use a `--remove-v1` flag, so I try that and it deletes all the existing todos.  If I run `yarn lint` now it completes and shows me all the errors that were previously todos.  So next I run `npx ember-template-lint . --update-todo` to recreate my todos in the new format, which works.  I now have a `.lint-todo` file and when I run `yarn lint` it passes.  However, If I switch to another branch in git, then switch back to this branch, and then run `yarn lint` again (after install) it fails with all the todos again, even though the `.lint-todo` file is there.  This also happens on our CI servers.

Is there some upgrade step or configuration that I'm missing?  Thanks!

**Comment by scalvert** [comment]
Hey @adc-mhaugen, sorry you're having issues with todos.

What you've done is precisely what I would expect, right up until switching branches and things not working again. 

Is it possible to provide a minimal reproduction of the issue in a repo somewhere? You can likely just use `ember new` to create a new repo, which you can then configure with the todos.

**Comment by adc-mhaugen** [comment]
Good news @scalvert, I was able to reproduce in a new empty addon project: https://github.com/adc-mhaugen/template-lint-upgrade.  There are two branches:

1. `main` is the original state with `ember-template-lint@3.4.2` and a `.lint-todo` folder.
2. `upgrade` uses `ember-template-lint@4.3.0` with the `.lint-todo` folder converted to a file (using the todo migrator tool).

After upgrading and converting todos the `yarn lint` passed, but once I switched to `main` and then back to `upgrade` it no longer passes.

Please let me know if there is anything I can do to help.

**Comment by scalvert** [comment]
@adc-mhaugen thanks so much for taking the time to create this repro. This'll help immensely. I'll see if I can figure out what's happening today and will report back.

**Comment by scalvert** [comment]
I took a look at this and it appears this is working as expected.

In `main`:

![](https://cdn.discordapp.com/attachments/666416704418611233/956235432130117632/Screen_Shot_2022-03-23_at_9.58.05_AM.png)

In `upgrade`:

![](https://cdn.discordapp.com/attachments/666416704418611233/956235838528831518/Screen_Shot_2022-03-23_at_9.59.39_AM.png)

In both cases, part of the issue I see is that you're configuring your `yarn lint:hbs` script to use `--quiet`, which suppresses todos in all cases.
