### ISSUE TITLE
Can we use find-up when looking for the config file?

### ISSUE THREAD

**Issue by yangpiao** [ember-template-lint/ember-template-lint#2467]
Currently in `resolveProjectConfig` (https://github.com/ember-template-lint/ember-template-lint/blob/master/lib/get-config.js#L50), we use `findUpSync` when `options.configPath` is not present, but not if otherwise. Can we update the `if` block to use find-up as well? `options.configPath` has a default value (`.template-lintrc.js`), so most of the time we won't even go into the `else` block. Using `find-up` would make managing config in yarn workspaces easier. Thanks.

```js
  if (options.configPath) {
    // update this to use `find-up`?
    configPath = path.resolve(workingDir, options.configPath);
    // ...
  } else if (options.configPath === false) {
    return {};
  } else {
    configPath = findUpSync(CONFIG_FILE_NAME, {
      cwd: workingDir,
    });
    // ....
  }
```

**Comment by scalvert** [comment]
I think this is fine to do. This helps with situations when users are using `yarn workspaces`, but want a single configuration file while having the CLI as a dependency of one or many sub-packages.
