### ISSUE TITLE
Proposal to expand `no-redundant-landmark-role` to lint against redundancy for all elements with ARIA role support

### ISSUE THREAD

**Issue by judithhinlung** [ember-template-lint/ember-template-lint#2485]
This proposes expanding the coverage of `no-redundant-landmark-role` to lint against all HTML elements with default or implicit ARIA roles.  Since these semantic elements already have browser support for their respective ARIA roles, adding another role attribute will add  and should be avoided.
This change will make `no-redundant-landmark-role` analogous to [JSX's `no-redundant-roles](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/docs/rules/no-redundant-roles.md) rule. 

Reference: [ARIA Spec, ARIA Adds Nothing to Default Semantics of Most HTML Elements](https://www.w3.org/TR/using-aria/#aria-does-nothing)

**Comment by bmish** [comment]
Would this involve renaming the rule (which can happen during a major release if needed) or just adding options (which can be enabled by default in a major release)?

**Comment by judithhinlung** [comment]
I would like to implement this as an option in the config so that it won't be a breaking change.
