### ISSUE TITLE
`no-unsupported-role-attributes` throws an error

### ISSUE THREAD

**Issue by boris-petrov** [ember-template-lint/ember-template-lint#2514]
Namely `error  Cannot read properties of undefined (reading '0')  undefined`. Gives it on a bunch of files, the simplest one being just: `<ItemCheckbox @model={{@model}} @checkable={{@checkable}} />`.

**Comment by bmish** [comment]
@judithhinlung

**Comment by Turbo87** [comment]
if you need a reproduction on a real repo: https://github.com/rust-lang/crates.io/pull/4820 :)
