### ISSUE TITLE
<s> and <u> are not obsolete anymore (no-obsolete-elements)

### ISSUE THREAD

**Issue by sukima** [ember-template-lint/ember-template-lint#2588]
As far as I can tell from the [WATWG HTML spec](https://html.spec.whatwg.org/#non-conforming-features)—first link in the [referenced documentation](https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/no-obsolete-elements.md)—they explain that “Elements in [non-conforming features] list are entirely obsolete, and must not be used by authors” for which the only reference to `<s>` is the following:

> **strike**
> Use [`del`](https://html.spec.whatwg.org/#the-del-element) instead if the element is marking an edit, otherwise use [`s`](https://html.spec.whatwg.org/#the-s-element) instead.

I have been unable to find any reference to the deprecation of the `<s>` element.

**Comment by bmish** [comment]
It was added here: https://github.com/ember-template-lint/ember-template-lint/pull/1532

The link from that PR seems to be broken. Need to see where the page was moved to so we can check the original source for this.

**Comment by sukima** [comment]
Seems per that PR that it is obsolete but there appears to be no record of that and as noted above the current living spec only references it as an alternative. However, `<u>` is also not there in the spec. So how do we know it is obsolete and what is the alternative.

**Comment by sukima** [comment]
@bmish Best I can tell it was moved here: https://html.spec.whatwg.org/#non-conforming-features but reading through that has no mention to `<b>`, `<u>`, or `<s>`. It does say `<s>` replaced `<strike>` which is even _more_ confusing.

**Comment by sukima** [comment]
I found this [obscure reference](https://www.linkedin.com/pulse/obsolete-deprecated-tags-html5-shadi-namrouti):

> `<s>` Was similar to the deprecated `<strike>`. It is redefined as non-accurate text.

**Comment by bmish** [comment]
I found an archived version of the original source showing `<s>` and `<u>` in the list of `Non-conforming features - Elements in the following list are entirely obsolete, and must not be used by authors - Use CSS instead`.

https://web.archive.org/web/20220407040721/https://dev.w3.org/html5/pf-summary/obsolete.html

> 13.2 Non-conforming features
> Elements in the following list are entirely obsolete, and must not be used by authors:
> 
> [applet](https://web.archive.org/web/20220407040721/https://dev.w3.org/html5/pf-summary/obsolete.html#the-applet-element)
> Use [embed](https://web.archive.org/web/20220407040721/https://dev.w3.org/html5/pf-summary/embedded-content-0.html#the-embed-element) or [object](https://web.archive.org/web/20220407040721/https://dev.w3.org/html5/pf-summary/embedded-content-0.html#the-object-element) instead.
> 
> acronym
> Use [abbr](https://web.archive.org/web/20220407040721/https://dev.w3.org/html5/pf-summary/text-level-semantics.html#the-abbr-element) instead.
> 
> dir
> Use [ul](https://web.archive.org/web/20220407040721/https://dev.w3.org/html5/pf-summary/semantics.html#the-ul-element) instead.
> 
> [frame](https://web.archive.org/web/20220407040721/https://dev.w3.org/html5/pf-summary/obsolete.html#frame)
> [frameset](https://web.archive.org/web/20220407040721/https://dev.w3.org/html5/pf-summary/obsolete.html#frameset)
> noframes
> Either use [iframe](https://web.archive.org/web/20220407040721/https://dev.w3.org/html5/pf-summary/embedded-content-0.html#the-iframe-element) and CSS instead, or use server-side includes to generate complete pages with the various invariant parts merged in.
> 
> isindex
> Use an explicit [form](https://web.archive.org/web/20220407040721/https://dev.w3.org/html5/pf-summary/forms.html#the-form-element) and [text field](https://web.archive.org/web/20220407040721/https://dev.w3.org/html5/pf-summary/forms.html#text-state-and-search-state) combination instead.
> 
> listing
> xmp
> Use [pre](https://web.archive.org/web/20220407040721/https://dev.w3.org/html5/pf-summary/semantics.html#the-pre-element) and [code](https://web.archive.org/web/20220407040721/https://dev.w3.org/html5/pf-summary/text-level-semantics.html#the-code-element) instead.
> 
> noembed
> Use [object](https://web.archive.org/web/20220407040721/https://dev.w3.org/html5/pf-summary/embedded-content-0.html#the-object-element) instead of [embed](https://web.archive.org/web/20220407040721/https://dev.w3.org/html5/pf-summary/embedded-content-0.html#the-embed-element) when fallback is necessary.
> 
> plaintext
> Use the "text/plain" [MIME type](https://web.archive.org/web/20220407040721/https://dev.w3.org/html5/pf-summary/infrastructure.html#mime-type) instead.
> 
> basefont
> big
> blink
> center
> font
> [marquee](https://web.archive.org/web/20220407040721/https://dev.w3.org/html5/pf-summary/obsolete.html#the-marquee-element-0)
> s
> spacer
> strike
> tt
> u
> Use CSS instead.

**Comment by bmish** [comment]
So it seems `<s>` was deprecated but might have been un-deprecated and repurposed? Can you find any documentation showing that change and when it happened? If the list of deprecated elements changes over time, that's fine, but just want to make sure we are correctly understanding any changes to the spec before we pull the trigger.

**Comment by sukima** [comment]
@bmish It was quite the journey but I was able to bisect the living HTML standard [repository](https://github.com/whatwg/html) and found [the commit](https://github.com/whatwg/html/commit/40c807c2c3525301b13ac46ae2f2e77572efe486) when `<s>` was removed from the obsolete list. The reasoning for this is well documented in [the bug report](http://www.w3.org/Bugs/Public/show_bug.cgi?id=9429).

**Comment by sukima** [comment]
Notably, Same issue with `<u>`. Was removed from the obsolete list in [this commit](https://github.com/whatwg/html/commit/4cf0cdcf02889d5f75b1f8803e94070968de1a4d) to fix [this bug](https://www.w3.org/Bugs/Public/show_bug.cgi?id=10838).

**Comment by bmish** [comment]
Thanks for your investigation. It sounds like we can update the rule to match the current deprecated/obsolete elements as I'm assuming that's why @MelSumner intended with the rule. Although most people would still want to use CSS instead of these particular elements right?

**Comment by sukima** [comment]
Like `<i>` and `<b>` are not obsolete but repurposed so was `<u>` and `<s>`. There are _semantic_ reasons to use `<u>` and `<s>` according to the latest specs¹

For styling purposes yet the developer would and should use CSS but from a pure semantic perspective the above elements provide a different meaning then what they used to have when they were just style presentation tags.

 ¹ [`u` spec](https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-u-element) [`s` spec](https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-s-element)
