### ISSUE TITLE
Can't disable a plugin

### ISSUE THREAD

**Issue by psbanka** [ember-template-lint/ember-template-lint#261]
If you create a plugin for ember-template-lint and then try to disable it, this won't work, for the following reasons:

1. if you disable only the rule that is associated with a plugin, the code here: https://github.com/rwjblue/ember-template-lint/blob/master/lib/rules/base.js#L72 will error out because plugins are not recognized as rules (only the rules that ship with `ember-template-lint` are recognized as rules.
2. If you disable all rules, the plugin's configuration does not seem to change in time for it to process the directive. I tried to log the events that were happening and their sequence, and this is what I found:

```
(output from the plugin, in its visitor() method, logging its config:)
this.config { min: 20, max: 100 }
-> rules/base.js, line 401 (https://github.com/rwjblue/ember-template-lint/blob/master/lib/rules/base.js#L401)
-> rules/base.js line 413 (https://github.com/rwjblue/ember-template-lint/blob/master/lib/rules/base.js#L401)
-> returning { tree: false, value: false }
-> rules/base.js line 337 (https://github.com/rwjblue/ember-template-lint/blob/master/lib/rules/base.js#L337)

/Users/psbanka/dev/copy-tango/app/pods/support/docs-search/template.hbs
  -:-  error  Template length of 12 is smaller than 20  length-validation
```

For some reason the pugins seem to be processed *before* instructions are processed and therefore their configs do not get updated.

**Comment by rwjblue** [comment]
I haven't had much time to dig into this yet, sorry for the delays.  Would you mind throwing together a demo app that I could pull down and test?

**Comment by rwjblue** [comment]
Finally dug into this a bit, and we need to update the implementation for `_isRuleName` so that it is aware of all configured plugins (not just those that are hard coded in the repo).

Up for taking a crack at it?

**Comment by rwjblue** [comment]
@psbanka - Up for taking a shot at this?

**Comment by patocallaghan** [comment]
@psbanka @rwjblue I just came across this issue today.

I'm keen to have this functionality soon-ish so unless there is a PR close to completion I'd like to take a stab at it? Would that be okay?

**Comment by rwjblue** [comment]
absolutely!

**Comment by patocallaghan** [comment]
Awesome, I’ll put something together 👍

**Comment by patocallaghan** [comment]
@rwjblue I finally got around to looking at this and am not entirely certain I'm going the right way about it.

I'm not exactly familiar with the codebase. I was planning on adding something called rules/plugins.js which will essentially operate the same way as rules/index.js and just load and export all the plugins. I then plan on using this within `_isRuleName`. But I'm not exactly sure how to get access to the loaded plugins?

**Comment by patocallaghan** [comment]
I've added a WIP spike of a fix in https://github.com/ember-template-lint/ember-template-lint/pull/718. Would appreciate any feedback

**Comment by patocallaghan** [comment]
@rwjblue any thoughts on the approach I used in https://github.com/ember-template-lint/ember-template-lint/pull/718 and how we could properly access the config?
