### ISSUE TITLE
`no-negated-condition` rule could detect and fix `(not (eq...` and others

### ISSUE THREAD

**Issue by godric3** [ember-template-lint/ember-template-lint#2655]
Negation connected with some other helpers could be simplified:
- `(not (eq ...))` -> `(not-eq ...)`
- `(not (not-eq ...))` -> `(eq ...)`
- `(not (gt ...))` -> `(lte ...)`
- `(not (gte ...))` -> `(lt ...)`
- `(not (lt ...))` -> `(gte ...)`
- `(not (lte ...))` -> `(gt ...)`

Cases with eq and not-eq looks harmless to autofix, but rest may not always be desirable so it could be enabled with some setting.

**Comment by bmish** [comment]
Why wouldn't they all be safe and desirable?

I'm a big fan of boolean simplification rules. Such rules exist in other plugins, e.g.
* https://github.com/platinumazure/eslint-plugin-qunit/blob/master/docs/rules/no-negated-ok.md

**Comment by bmish** [comment]
This could be part of the next major release #2319 as a breaking change if the PR is ready.

Could also put it all behind a new option on the rule (off by default) to avoid a breaking change and release it sooner (with the option to be enabled by default in next major release).

**Comment by godric3** [comment]
> Why wouldn't they all be safe and desirable?

That was just a remark as I encountered situation where some one wanted to have comparisons always done in one direction even if that would require negation. But objectively looking it won't break anything and code will be simplified :)

**Comment by bmish** [comment]
If someone has a personal preference on that, they can disable the rule :) but boolean simplification is a good idea for a rule.

**Comment by godric3** [comment]
Hmm as some code for that would be based on code from #2653 maybe we will make both helpers mentioned here and double negation hidden behind the option `simplifyHelpers`(?) that will be false on default and changed to true on next major release?
If yes then I would rework existing PR to include this issue there
