### ISSUE TITLE
`--fix` for `attribute-order` moves around comments

### ISSUE THREAD

**Issue by boris-petrov** [ember-template-lint/ember-template-lint#2693]
```hbs
<Foo
  class="asd asd qwe rty asd zxc asd qwe asd zxc asd qwe asd zxc qwe qwe qwe qwe qwe asd zxc qwe qwe qwe qwe qwe"
  {{! @glint-expect-error }}
  @foo={{1}} />
```

(the long `class` is for Prettier to not make the whole thing on one line)

Running `--fix` on that leads to:

```hbs
<Foo
  @foo={{1}}
  class="asd asd qwe rty asd zxc asd qwe asd zxc asd qwe asd zxc qwe qwe qwe qwe qwe asd zxc qwe qwe qwe qwe qwe"
  {{! @glint-expect-error }}
/>
```

Which is not nice because the comment is supposed to go with the `@foo` argument but it was moved at the end. This is a breaking change for `glint` directives. And just an annoyance for normal comments. :)

Not sure if that's a bug that's fixable though...

**Comment by bmish** [comment]
@rob-long? Let's definitely make sure this significant comment position is respected. Maybe we can move the comment with the subsequent element?

**Comment by rob-long** [comment]
@bmish fix for this and https://github.com/ember-template-lint/ember-template-lint/issues/2692: https://github.com/ember-template-lint/ember-template-lint/pull/2701
