### ISSUE TITLE
no-unknown-arguments-for-builtin-components: Argument "@route" or "@query" is required for <LinkTo /> component

### ISSUE THREAD

**Issue by jelhan** [ember-template-lint/ember-template-lint#2700]
The `no-unknown-arguments-for-builtin-components` complains about `<LinkTo />` component having `@model` (or `@models`) argument only. It requires to have either `@route` or `@query`. But having only `@model` or `@models` should be fine.

`<LinkTo />` having only `@model` or `@models` transitions to other dynamic segments of the same route keeping query parameters untouched. This is covered by public API as far as I know.

Originally the rule even required `@route` to be present always. Addressing #1802 it was extended to either `@route` or `@query`. But the case of `@model` or `@models` only seem to be missed on that one.

**Comment by geneukum** [comment]
Good catch, I think that you're right per https://github.com/emberjs/ember.js/blob/master/packages/%40ember/-internals/glimmer/lib/components/link-to.ts#L291.

I opened https://github.com/ember-template-lint/ember-template-lint/pull/2726 to hopefully resolve this issue.

**Comment by jelhan** [comment]
Thanks a lot for fixing it!
