### ISSUE TITLE
Attribute Order Breaks For Link Components

### ISSUE THREAD

**Issue by Alonski** [ember-template-lint/ember-template-lint#2710]
Not sure why but Attribute Order breaks when using `<Link>` component:
Input:
```hbs
<Link
  @b="taco"
  @a={{a}}
>
  {{taco}}
</Link>
```
Output after ETL Fix:
```handlebars
<Link @a={{a}} @b="taco">
  {{taco}}
```
Notice the missing closing `</Link>` tag

**Comment by Alonski** [comment]
CC @rob-long If you want to take a look
Thanks for doing this work BTW so awesome!

**Comment by bertdeblock** [comment]
My guess would be that the issue is more about the component having the same name as a void tag.
For example, the same happens if you use `Meta` as the component's name.

**Comment by bertdeblock** [comment]
I think we need this fix to be released in the VM: https://github.com/glimmerjs/glimmer-vm/pull/1390.

**Comment by bertdeblock** [comment]
FYI, there's a [new release](https://github.com/glimmerjs/glimmer-vm/releases/tag/v0.84.3), so we should be able to fix this issue.
