### ISSUE TITLE
no-redundant-role: False positive for `role=list` on `<ul>`

### ISSUE THREAD

**Issue by Turbo87** [ember-template-lint/ember-template-lint#2713]
Due to https://bugs.webkit.org/show_bug.cgi?id=170179 the linter should not warn about `<ul role="list">`.

**Comment by bmish** [comment]
Seems like a reasonable fix. CC: @MelSumner @rajasegar @judithhinlung

**Comment by Turbo87** [comment]
for more context: https://www.scottohara.me/blog/2019/01/12/lists-and-safari.html :)
