### ISSUE TITLE
is there a way to ignore?

### ISSUE THREAD

**Issue by eric-g-97477** [ember-template-lint/ember-template-lint#2743]
Does ember-template-lint look at any ignore file for files it should not process?

Does it support something similar to /* eslint-disable */ ?

**Comment by bmish** [comment]
For posterity:

* `--ignore-pattern`: https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/workflow.md
* `{{!-- template-lint-disable no-bare-strings  --}}`: https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/configuration.md
