### ISSUE TITLE
no-duplicate-id rule errors when using ember's built-in unique-id helper

### ISSUE THREAD

**Issue by steveszc** [ember-template-lint/ember-template-lint#2777]
When two elements both assign `id={{unique-id}}` the no-duplicate-ids rule triggers an error.

Since `unique-id` is a built-in helper that always returns a unique id this should not be a violation.

![unique-id](https://user-images.githubusercontent.com/6877934/213549617-f56f6b8a-a43b-4596-b16b-735ac9072f53.png)

**Comment by bmish** [comment]
Good point. I see this helper was added here: https://rfcs.emberjs.com/id/0659-unique-id-helper/

Should be straightforward to ignore it. PR welcome.

**Comment by steveszc** [comment]
I took a look at the fix PR and I think `{{(unique-id)}}` also needs to be added to the ignore list and the "good" test cases? 
I am on mobile right now so I haven't been able to verify on my own but I think I remember the lint rule also errored when the helper is called with parens.

Can we re-open until that is fixed?

**Comment by bmish** [comment]
CC: @lifeart

**Comment by lifeart** [comment]
Do we really have a use-case where we execute it like this?

**Comment by steveszc** [comment]
Isn't it required for strict mode templates? I think argument-less helpers have to be invoked with parens. (Assuming this RFC is still valid)

https://rfcs.emberjs.com/id/0496-handlebars-strict-mode/

**Comment by steveszc** [comment]
I guess the paren-less style will still be valid for the id html attribute, but it is also still valid to call it with parens.

**Comment by lifeart** [comment]
I think RFC a little bit out of dated, because for `gts` we already have strict mode enabled (as I recap), and this condition working: https://github.com/lifeart/demo-ember-vite/blob/master/src/components/HelloWorld/sample.gts#L4
