### ISSUE TITLE
Enable new rules for 0.9.0.

### ISSUE THREAD

**Issue by rwjblue** [ember-template-lint/ember-template-lint#282]
To be added to the recommended config for 0.9.0:

- [ ] `no-inline-styles`
- [ ] `linebreak-style`
- [ ] `no-duplicate-attributes`
- [ ] `table-groups`
- [ ] `attribute-indentation` (with `{ 'process-elements': true }`)
- [ ] `no-unnecessary-concat`
- [ ] `no-input-block`
- [ ] `no-input-tagname`
- [ ] `no-unbound`
- [ ] `no-outlet-outside-routes`
- [ ] `no-partial`
- [ ] `no-unnecessary-concat`
- [ ] `quotes`
- [ ] `no-attrs-in-components`
- [ ] `no-shadowed-elements`

To be removed from the recommended config for 0.9.0:

- [ ] `deprecated-inline-view-helper`

**Comment by Turbo87** [comment]
should we enable `no-unnecessary-concat` by default too?

**Comment by rwjblue** [comment]
Just updated, added the following:

- [ ] `no-unnecessary-concat`
- [ ] `no-input-block`
- [ ] `no-input-tagname`
- [ ] `no-unbound`
- [ ] `no-outlet-outside-routes`
- [ ] `no-partial`
- [ ] `no-trailing-dot-in-path-expression`
- [ ] `no-unnecessary-concat`

**Comment by rwjblue** [comment]
Updated the main description with:

To be added to the recommended config for 0.9.0:

- [ ] `quotes`
- [ ] `no-attrs-in-components`

To be removed from the recommended config for 0.9.0:

- [ ] `deprecated-inline-view-helper`

**Comment by rwjblue** [comment]
Added `no-shadowed-elements` to the list.

**Comment by rwjblue** [comment]
Closed by https://github.com/ember-template-lint/ember-template-lint/pull/457
