### ISSUE TITLE
Changes for table-group rule.

### ISSUE THREAD

**Issue by rwjblue** [ember-template-lint/ember-template-lint#285]
Per [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/table) the allowed contents of a `<table>` are:

> In this order:
> 1. an optional `<caption>` element,
> 2. zero or more `<colgroup>` elements,
> 3. an optional `<thead>` element,
> 4. either one of the following:
>   i) zero or more `<tbody>` elements
>   ii) one or more `<tr>` elements
> 5. an optional `<tfoot>` element

We are intentionally disallowing the option in 4 above (e.g. we require `<tr>` to be in `<tbody>`), but we still need to account for:

- [x] `<caption>`
- [x] `<colgroup>`

We also need to enforce the ordering that is mentioned in the spec...

**Comment by rwjblue** [comment]
@t-sauer - Do you think you might have time to look into this?

**Comment by t-sauer** [comment]
I will take a look

**Comment by rwjblue** [comment]
Reopening because we still need to enforce ordering.

**Comment by rwjblue** [comment]
@initram - Do you think we should close this now that #846 is landed? Not sure that we can do too much more...

**Comment by initram** [comment]
I think we should close this now. If anyone feels that it is insufficient, then a new issue can be created (or this can be reopened)
