### ISSUE TITLE
link-rel-noopener false-positive

### ISSUE THREAD

**Issue by boris-petrov** [ember-template-lint/ember-template-lint#380]
We have a number of places where we use `rel="noreferrer noopener"` which is not OK according to `link-rel-noopener` as it wants it to be `noopener noreferrer`. This means exactly the same, or am I mistaken?

**Comment by rwjblue** [comment]
Nope, I think you are definitely correct. Mind sending in a PR fixing?

**Comment by boris-petrov** [comment]
Done.
