### ISSUE TITLE
Reenabling template rule causes template lint tests to fail

### ISSUE THREAD

**Issue by blamens** [ember-template-lint/ember-template-lint#417]
Since today I am getting failing linter tests in my test suite on templates that reenable the `bare-strings` rule.

This is causing failing tests:
```
{{!-- template-lint-disable bare-strings --}}
<i class="material-icons">folder_open</i>
{{!-- template-lint-enable bare-strings --}}
```

Exception:
```my-app/components/foo-bar/template.hbs
  -:-  error  Cannot read property 'indexOf' of undefined  undefined
@ 1 ms
Expected:     
true
Result:     
false
Source:     
    at Object.<anonymous> (http://localhost:7357/assets/tests.js:12058:12)
    at runTest (http://localhost:7357/assets/test-support.js:4199:30)
    at Test.run (http://localhost:7357/assets/test-support.js:4185:6)
    at http://localhost:7357/assets/test-support.js:4406:12
    at advanceTaskQueue (http://localhost:7357/assets/test-support.js:3798:6)
    at advance (http://localhost:7357/assets/test-support.js:3779:4)
```

This works:
```
{{!-- template-lint-disable bare-strings --}}
<i class="material-icons">folder_open</i>
```

**Comment by rwjblue** [comment]
I assume this is related to https://github.com/ember-template-lint/ember-template-lint/pull/377, but I cannot reproduce the issue you are seeing yet.

When I take that snippet and run it through the linter, I do not get any errors.  Can you share what your original `bare-strings` config is? Can you test your template by reducing it to just the parts required to fail?

**Comment by blamens** [comment]
I dont know if this effects any of it but this is my ``.template-lintrc.js`:
```/* eslint-env node */
'use strict';

module.exports = {
	extends: 'recommended',
	rules: {
		'bare-strings': true,
		'block-indentation': 'tab'
	}
};```

I'll try and narrow it down some more.

**Comment by rwjblue** [comment]
There was another recent change that may be related: https://github.com/ember-template-lint/ember-template-lint/pull/412.  Specifically we now consider `aria-label`, `aria-placeholder`, `aria-roledescription`, `aria-valuetext` to be considered by the no-bare-strings rule.  Do the templates in question have any of those attributes?

**Comment by blamens** [comment]
Here is another full template that's throwing. Ill try and remove some stuff (like the `data-test-selectors` might be doing something like that).

```
<div class="error-block">
	<div class="error-block__code">{{code}}</div>
	<div class="error-block__error">
		{{!-- template-lint-disable bare-strings --}}
		<i class="material-icons error-block__icon">error_outline</i>
		{{!-- template-lint-enable bare-strings --}}
		<h3 data-test-error-text>{{text}}</h3>
	</div>
	<div class="error-block__link">
		<div data-test-error-block-message>{{t "error.error-block.suggestion"}}</div>
		<ul class="error-block__link__list">
			{{#if (feature-flag "dashboardsOnly")}}
				<li>{{#link-to "my-other-route" 1}}{{t "myapp.menu.dashboard"}}{{/link-to}}</li>
			{{else}}
				<li>{{#link-to "my-route"}}{{t "error.error-block.default_scorecard"}}{{/link-to}}</li>
				<li>{{#link-to "actions"}}{{t "error.error-block.actions"}}{{/link-to}}</li>
			{{/if}}
		</ul>
	</div>
</div>
```

Oh and im reffing `ember-cli-template-lint` like this in my `package.json` by the way;
`"ember-cli-template-lint": "0.7.5",`

**Comment by blamens** [comment]
Bingo! If I remove `data-test-error-block-message` and `data-test-error-text` its passing.

**Comment by rwjblue** [comment]
Awesome, thank you for sharing your template and config, I am able to reproduce.  Digging in to figure out what is going on now...

**Comment by blamens** [comment]
If I change my `.template-lintrc.js` to:

```
/* eslint-env node */
'use strict';

module.exports = {
	extends: 'recommended',
	rules: {
		'no-bare-strings': true,
		'block-indentation': 'tab'
	}
};
```
all is working fine again (templates being linted properly and throwing on bare-strings).

Seems like the `bare-strings` rule in the config is not backwards compatible. Ill change it to `no-bare-strings` for now. Thanks for your time.
