### ISSUE TITLE
Only report errors / hide warnings

### ISSUE THREAD

**Issue by srt4rulez** [ember-template-lint/ember-template-lint#428]
Is it possible to only report errors / hide warnings for the CLI? Something like the "--quiet" option in eslint?

I was looking to integrate this in a CI setup with the "pending" config so my team could start using it, but I found out pretty quick that if there are errors, it also shows all other warnings too! So finding the error in the thousands of warnings doesn't really work. 

I played around with the code a bit and was able to make such an option, so I could take a crack at making a PR if you guys are open to it?

**Comment by rwjblue** [comment]
Ya, definitely happy for a PR here...
