### ISSUE TITLE
Whitelisted empty bare string causes an infinite loop

### ISSUE THREAD

**Issue by joankaradimov** [ember-template-lint/ember-template-lint#429]
I am using `ember-template-lint` via `ember-cli-template-lint`. There appears to be an unhandled edge case in the configuration.

Putting an empty string in the whitelisted bare strings in `.template-lintrc.js` results in an infinite loop during the build.

```javascript
rules: {
  'no-bare-strings': {
    whitelist: ['']
  }
}
```

**Comment by rwjblue** [comment]
Nice catch! Mind sending in a patch?  I _think_ the easiest fix is to modify `parseConfig` [here](https://github.com/ember-template-lint/ember-template-lint/blob/d5f7a245ffdd5a86f193d144e733365181221cb2/lib/rules/lint-no-bare-strings.js#L78) and [here](https://github.com/ember-template-lint/ember-template-lint/blob/d5f7a245ffdd5a86f193d144e733365181221cb2/lib/rules/lint-no-bare-strings.js#L85-L87) to filter out empty strings...

**Comment by joankaradimov** [comment]
> Nice catch!

Thanks.

> Mind sending in a patch?

Not at all. I'd love to. But it would have to wait until the weekend.

**Comment by rwjblue** [comment]
Sounds good!
