### ISSUE TITLE
Cannot read property '0' of undefined with Angle Brackets when passing @something={{false}}

### ISSUE THREAD

**Issue by josemarluedke** [ember-template-lint/ember-template-lint#443]
I have the following code snippet:

```hbs
<PowerSelect
  @selected={{@pageSize}}
  @options={{this.availablePageSizes}}
  @searchEnabled={{false}}
  @onchange={{action this.changePageSize}} as |size|>
  {{size}}
</PowerSelect>
```
And then I get the following error from template lint:

```
  -:-  error  Cannot read property '0' of undefined  undefined
```

If I remove `@searchEnabled={{false}}` I don't get any errors.

**Comment by rwjblue** [comment]
Can you confirm which version of `ember-template-lint` is being used? A number of changes related to angle bracket components just landed and I'm not sure if this is caused by one of them or a duplicate of something already fixed...

**Comment by rwjblue** [comment]
Awesome, thank you!
