### ISSUE TITLE
Add no-unnecessary-concat to rule documentation

### ISSUE THREAD

**Issue by bryanhickerson** [ember-template-lint/ember-template-lint#476]
Info in [originating issue](https://github.com/ember-template-lint/ember-template-lint/issues/350) should be in docs instead of needing to look up the associated issue.

**Comment by rwjblue** [comment]
Totally agreed! Would love help getting this squared away...

**Comment by Willibaur** [comment]
@rwjblue I have created documentation with [PR-513](https://github.com/ember-template-lint/ember-template-lint/pull/513)

Thanks

**Comment by rwjblue** [comment]
Fixed by #513
