### ISSUE TITLE
Disable Deprecations

### ISSUE THREAD

**Issue by differentMonster** [ember-template-lint/ember-template-lint#479]
Hey guys:
i am having some ember deprecations on my cmd, is useable and i want to keep it but the deprecations error in cmd are confusing me , is there a way this addon cant target the addon that causing that error and turn if off ?

the error

DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: front -> ember-cli-crudities -> ember-cli-dynamic-model -> ember-network -> ember-cli-babel

i want to switch off the error but still keep using it.

**Comment by rwjblue** [comment]
Hmm, these deprecations seem unrelated to ember-template-lint. You should look at upgrading the dependencies that are mentioned in that error message.

Closing for now (please let me know if I've misunderstood)...
