### ISSUE TITLE
All default rules change state to disabled as soon as I add one rule to .template-lintrc.js

### ISSUE THREAD

**Issue by Willibaur** [ember-template-lint/ember-template-lint#489]
I have a really weird situation, where  if I use 

```bash
node_modules/.bin/ember-template-lint app/templates --verbose
``` 

with no rules set within `.template-lintrc.js` 

```js
module.exports = {
  extends: 'recommended',
}
```
it lints all errors correctly, but as soon as I add one rule, all other rules change state to disable, is that normal behaviour?, I could not find any info within documentation.

Thanks

I have narrowed the problem and found that as soon as I add  this rule :point_right: `'simple-unless': { maxHelpers: --1 },` all other rules become disabled

```js
module.exports = {
  extends: 'recommended',

  rules: {
    'simple-unless': { 'maxHelpers': --1 },
  }
}
```

**Comment by rwjblue** [comment]
What if you use another (positive) integer there?

**Comment by Willibaur** [comment]
I tried `'simple-unless': { 'maxHelpers': 2 }` and got the following error @rwjblue 

```sh
  -:-  error  The simple-unless rule accepts one of the following values.
  * boolean -- `true` for enabled / `false` for disabled
  * object --
    *  `whitelist` -- array - `['or']` for specific helpers / `[]` for wildcard
    *  `maxHelpers` -- number
You specified `{"maxHelpers":2}`  undefined
```

**Comment by rwjblue** [comment]
Weird! Definitely a bug in parsing for that rule...

**Comment by rwjblue** [comment]
Finally got around to digging into this, and ultimately found two different bugs to be fixed:

* invalid config just disables all rules
* we required _both_ `whitelist` and `maxHelpers` to be set, but should allow one or the other also

Both should be fixed shortly...

**Comment by Willibaur** [comment]
Thank you very much @rwjblue
