### ISSUE TITLE
Unexpected {{partial}} usage

### ISSUE THREAD

**Issue by papakay** [ember-template-lint/ember-template-lint#493]
Please i have a template lint error with the line of code below

```
{{partial "-sales-table-header"}}
```

Ember 3.4.1
Ember template lint 1.0.0.beta.1

**Comment by rwjblue** [comment]
Agree with @jherdman here. The exact intent of this rule is to help guide folks to avoiding partial usage...

**Comment by rwjblue** [comment]
Closing as not a bug (happy to reopen if I've miss-understood...)

**Comment by papakay** [comment]
@jherdman and @rwjblue Thanks for the insight and direction.
