### ISSUE TITLE
attribute-indentation configuration

### ISSUE THREAD

**Issue by lamabiker** [ember-template-lint/ember-template-lint#501]
Hi all,
Unless I am mistaken, we cannot currently configure the indentation size in the `attribute-indentation` rule.
The current indentation rule follows the globally configured convention (i.e 2 spaces), but it would be nice to be able to configure the `attribute-indentation` to a specific amount of spaces (in our case 4, or 2x2).

We currently indent components like this:
```hbs
{{inline-component
    attribute1=true
    attribute2=true
    attribute3=true}}

{{#block-component
    attribute1=true
    attribute2=true
    attribute3=true}}

  yielded content here

{{/block-component}}
```

In other words, would you have anything against something like this? :

```js
module.exports = {
  extends: 'recommended',

  rules: {
    'attribute-indentation': { 'indentation-size': 4 }
  }
};
```

Thanks!

**Comment by rwjblue** [comment]
Nope, sounds great! Would love a PR...

**Comment by rwjblue** [comment]
Hmm, I think we already support this? Would you mind double checking this:

```
module.exports = {
  extends: 'recommended',

  rules: {
    'attribute-indentation': { 'indentation': 4 }
  }
};
```

This is supported by the rule internally:

https://github.com/ember-template-lint/ember-template-lint/blob/a90656ae0c3659e68a1d13b38f9bc6d2161054ed/lib/rules/lint-attribute-indentation.js#L467-L469

If it works would you mind shooting off a docs update?
