### ISSUE TITLE
Custom path for Config?

### ISSUE THREAD

**Issue by krivaten** [ember-template-lint/ember-template-lint#527]
Looking through the source, it seems we are not currently able to define a custom location for the config. I see a few places where `options.config` is checked, but nowhere it is being set. Is this something you would accept a PR for?

If so, I was thinking of checking the `process.argv` for something like "config-path" before the `new Linter()` is invoked within "ember-template-lint.js" unless you had a different approach you would prefer?

**Comment by rwjblue** [comment]
Definitely seems reasonable to have a `—config-path` type command line argument...
