### ISSUE TITLE
undefined rule: 'Configuration stack out of sync with AST!'

### ISSUE THREAD

**Issue by jeneve** [ember-template-lint/ember-template-lint#529]
I have a linting error I can't understand:

it's triggered by whatever I put at the top of one file `app/templates/components/task-attachment.hbs`

```not ok 136 Chrome 69.0 - [2 ms] - TemplateLint: fc-client/templates/components/task-attachment.hbs
    ---
        actual: >
            false
        expected: >
            true
        stack: >
                at Object.<anonymous> (http://localhost:7357/assets/tests.js:5263:12)
                at runTest (http://localhost:7357/assets/test-support.js:4299:30)
                at Test.run (http://localhost:7357/assets/test-support.js:4285:6)
                at http://localhost:7357/assets/test-support.js:4506:12
                at advanceTaskQueue (http://localhost:7357/assets/test-support.js:3898:6)
                at advance (http://localhost:7357/assets/test-support.js:3879:4)
        message: >
            fc-client/templates/components/task-attachment.hbs should pass TemplateLint.

            fc-client/templates/components/task-attachment.hbs
              -:-  error  Configuration stack out of sync with AST!  undefined

        negative: >
            false
        Log: |
    ...
```

as you can see from above, the line numbers are null or undefined and the rule is undefined, so I am not sure where to begin debugging this.

Any help is greatly appreciated, and please let me know what other config or stacktrace might help!

**Comment by rwjblue** [comment]
I think an HTML snippet must have gotten stripped from your issue description, can you double check?

> it's triggered by whatever I put at the top of one file app/templates/components/task-attachment.hbs

I think maybe there was something stripped between `put` and `at` here...

**Comment by rwjblue** [comment]
Hmm, what version are you using? Seems like it’s still using glimmer-engine internally which we moved away from a while back. I wonder if updating to latest will fix...

**Comment by jeneve** [comment]
THANKS! I don't know how I overlooked that. Fixed in one.
