### ISSUE TITLE
feature request: no curly-components

### ISSUE THREAD

**Issue by jamesarosen** [ember-template-lint/ember-template-lint#539]
I'd love a rule to help transition from `{{foo-bar}}` to `<foo-bar>`. I don't know if it would be possible, though, since helpers would still need to be allowed.

**Comment by ppcano** [comment]
I think the rule could have a whitelist option to provide a list of allowed components, this option would help to have a smoother and incremental transition.

**Comment by axsuul** [comment]
@jamesarosen Don't you mean `{{foo-bar}}` to `<FooBar>`?

**Comment by jamesarosen** [comment]
I might. I believe when I opened this issue the plan was to have Ember follow the CustomElement requirement of a dash in component names.

**Comment by rwjblue** [comment]
I think this has been addressed, there is now a rule for `no-curly-component-invocations`.
