### ISSUE TITLE
attribute-indentation options for `as` part

### ISSUE THREAD

**Issue by luxferresum** [ember-template-lint/ember-template-lint#554]
Currently this is enforced:

```
{{#employee-details
  firstName=firstName
as |employee|
}}
  {{employee.fullName}}
{{/employee-details}}
```

However I really would prefer this:

```
{{#employee-details
  firstName=firstName
as |employee|}}
  {{employee.fullName}}
{{/employee-details}}
```

or this:

```
{{#employee-details
  firstName=firstName
  as |employee|
}}
  {{employee.fullName}}
{{/employee-details}}
```

could this be made configurable?

**Comment by rwjblue** [comment]
Ya, I totally agree with you, the `as |foo|}}` should be what we consider the closing by default. Having the `}}` on yet another separate line seems really annoying.

I would definitely love help pushing this forward...

**Comment by velrest** [comment]
Also for angle-bracket:
Current:
```js
<Component
  @name="something" as |c|
/>
```
Preferred:
```js
<Component
  @name="test"
  as |c|
/>
```
or
```js
<Component
  @name="test"
  as |c| />
```

**Comment by jelhan** [comment]
Especially not having the same defaults for curly-style component invocation syntax and angle-bracket component invocation syntax is confusing IMO.

```hbs
{{#employee-details
  firstName=firstName
as |employee|
}}
  {{employee.fullName}}
{{/employee-details}}
```
vs.
```hbs
<EmployeeDetails
  @firstName={{firstName}} as |employee|
>
  {{employee.firstName}}
</EmployeeDetails>
```

Should provide a codemod if we change that default.

**Comment by lolmaus** [comment]
CC @simonihmig .

**Comment by VincentMolinie** [comment]
Can anyone review my Pull Request 😅  ?
