### ISSUE TITLE
Align / join forces with Prettier

### ISSUE THREAD

**Issue by buschtoens** [ember-template-lint/ember-template-lint#562]
The Prettier team is working on [handlebars support](https://github.com/prettier/prettier/issues/5340). We should make sure, that our rules are 100 % compatible and maybe even join forces. 🤜🤛

**Comment by patocallaghan** [comment]
If anyone's interested to weigh in I've opened an issue to discuss the self-closing-void-element rule which currently being violated by the Prettier glimmer parser https://github.com/prettier/prettier/issues/6079

**Comment by rwjblue** [comment]
@dcyriller this one seems up your alley (I think this is _exactly_ what https://github.com/dcyriller/ember-template-lint-plugin-prettier is for?)..

**Comment by dcyriller** [comment]
It is done exactly for that! We use it in our apps to make sure our templates are always formatted with Prettier (with a job in CI). Thus, we notice bugs and improvements to be made in Prettier.

When a Prettier upgrade introduces a bug in a a file, either we add that file to `.prettierignore` or we delay Prettier upgrade until the bug has been fixed.

**Comment by Turbo87** [comment]
since https://github.com/ember-template-lint/ember-template-lint-plugin-prettier is solving this issue I'll go ahead and close this. thanks for working on it @dcyriller! 🎉
