### ISSUE TITLE
no-nested-interactive Rejects Elements in <details> Body

### ISSUE THREAD

**Issue by flwyd** [ember-template-lint/ember-template-lint#587]
The no-nested-interactive lint check rejects the following structure

```html
<details>
  <summary>Click to expand</summary>
  If you <button>click here</button> something will happen.
</details>
```

with a `Do not use <button> inside <details>  no-nested-interactive` error.

This seems like a perfectly reasonable HTML structure to me.  Per [MDN on the \<details\> element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details):

> A disclosure widget is typically presented onscreen using a small triangle which rotates (or twists) to indicate open/closed status, with a label next to the triangle. If the first child of the `<details>` element is a `<summary>`, the contents of the `<summary>` element are used as the label for the disclosure widget…  A `<details>` widget can be in one of two states. The default closed state displays only the triangle and the label inside `<summary>` (or a user agent-defined default string if no `<summary>`)… When the user clicks on the widget, or focuses it then presses the space bar, it "twists" open, revealing its contents.

And it specifies permitted content as "One `<summary>` element followed by flow content" without excluding interactive content.

A `<details>` element should not appear inside another interactive element and interactive elements shouldn't appear inside the `<summary>` element, but the body of an expanded `<details>` is not interactive and interactive elements inside a `<details>` behave as they would in a regular `<div>`.

**Comment by rwjblue** [comment]
Yes, I completely agree. Would accept a PR addressing...

**Comment by rwjblue** [comment]
In #640 @MelSumner mentioned that my suggestion that we should fix this may be incorrect (in other words, the current rule implementation is "correct").

@MelSumner - Can you help me understand why? I'd love to read up in the spec on this, have a link handy?

**Comment by MelSumner** [comment]
@rwjblue screen readers can't deal with nested interactive elements, and the `<details>` element was implemented in such a way that the `<details>` element is the one with the event listener (and the interactive bit ) and not the nested `<summary`> element, which would have been a much more reasonable default. 

If we can convince spec writers and browser implementors to change this, then the interactive elements could could be sibling elements and then it would be fine. Which would make sense. It's definitely a bummer (and wasted opportunity IMHO). 

I can dig up the specs too but Mozilla's docs show how the events work: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details

**Comment by Turbo87** [comment]
looks like we need a decision here... :D

@rwjblue any thoughts on the reasoning above?

**Comment by rwjblue** [comment]
I think we need to test this in practice with one or two screen readers to see what they actually do. I still think that I would expect the detail itself to be allowed to have interactive content, so I'd like to see if they do actually break / do a bad thing.

**Comment by MelSumner** [comment]
The `<details>` element is interactive and can't have interactive elements inside of it- breaks things for a11y. Here's an article that will hopefully help shed more light: https://daverupert.com/2019/12/why-details-is-not-an-accordion/

**Comment by Turbo87** [comment]
hmm, from that article it sounded more like the `<summary>` element is the interactive one 🤔 

> The core of the issue, which Scott pointed out, because <summary> has role="button", it eats the semantic content of elements inside it.

**Comment by rwjblue** [comment]
Agreed. I still think testing in actual screen readers is useful here.

**Comment by MelSumner** [comment]
@Turbo87 it was poorly implemented in browsers. Definitely agree with @rwjblue and suggest trying it out with assistive tech yourself- it will help make it clear how this one in particular doesn't behave the way we wish/expect it to. :+1:

**Comment by MelSumner** [comment]
Following up- I'm going to close the issue since the behavior is technically correct- `no-nested-interactive` rule should reject interactive elements inside of a `<details>` element.

More reading: 
- https://www.scottohara.me/blog/2018/09/03/details-and-summary.html
- https://gomakethings.com/i-was-wrong-about-javascript-free-dropdowns/
