### ISSUE TITLE
Document codemod for no-implicit-this

### ISSUE THREAD

**Issue by rwjblue** [ember-template-lint/ember-template-lint#602]
Add info for running https://github.com/dyfactor/dyfactor-plugin-disambiguate-locals to the docs for no-implicit-this.

**Comment by bartocc** [comment]
hi @rwjblue, I'd like to help on this one.

We are in the process of removing implicit `this` in our code base.

Is https://github.com/dyfactor/dyfactor-plugin-disambiguate-locals still active though? A small typo PR is still open from June 2018 and has not received any comment yet: https://github.com/dyfactor/dyfactor-plugin-disambiguate-locals/pull/2/files

**Comment by rwjblue** [comment]
OK, I think we have a much better thing to say here now. Folks should use https://github.com/ember-codemods/ember-no-implicit-this-codemod.

**Comment by bertdeblock** [comment]
It seems this ticket can be closed?
