### ISSUE TITLE
'unrecognized rule name' error when attempting to use comment to disable rule from plugin

### ISSUE THREAD

**Issue by bmish** [ember-template-lint/ember-template-lint#612]
It appears that rules defined in a custom plugin are not considered by the `_isRuleName` function that checks rule names.

```
{{! template-lint-disable my-rule-from-plugin }}
```

>   10:2  error  unrecognized rule name `my-rule-from-plugin` in template-lint-disable instruction  global

**Comment by gabrielcsapo** [comment]
Working on an PR to fix this

**Comment by rwjblue** [comment]
I think this was fixed as part of #261
