### ISSUE TITLE
[A11y] no-abstract-roles

### ISSUE THREAD

**Issue by MelSumner** [ember-template-lint/ember-template-lint#625]
## Rule Requested
Check to make sure that abstract roles are not used. 

## Example(s)
The HTML attribute `role` should never have the following values: 
- command
- composite
- input
- landmark
- range
- roletype
- section
- sectionhead
- select
- structure
- widget 
- window

## Reference
[https://www.w3.org/TR/wai-aria-1.0/roles#abstract_roles](https://www.w3.org/TR/wai-aria-1.0/roles#abstract_roles)

**Comment by lifeart** [comment]
I can take it

**Comment by rwjblue** [comment]
👍
