### ISSUE TITLE
no-invalid-interactive capturing onError

### ISSUE THREAD

**Issue by Frozenfire92** [ember-template-lint/ember-template-lint#663]
The following triggers this rule, where I would expect it not to as `onError` isn't a user interaction such as clicking

```hbs
<img
  src={{src}}
  alt={{alt}}
  onError={{action "onError"}}
>
```

**Comment by Frozenfire92** [comment]
It looks like there are existing exceptions

https://github.com/ember-template-lint/ember-template-lint/blob/master/lib/rules/lint-no-invalid-interactive.js#L81-L90

**Comment by rwjblue** [comment]
:+1: happy to add exceptions for this as needed, though I think it should be `onerror` not `onError`...
