### ISSUE TITLE
block-indentation rule conflicts with prettier for hbs block syntax

### ISSUE THREAD

**Issue by mike-north** [ember-template-lint/ember-template-lint#705]
### What prettier wants
```hbs
{{#link-to "index"}}
foo
{{/link-to}}
```
### What template-lint is happy with
```hbs
{{#link-to "index"}}
  foo
{{/link-to}}
```

Particularly if we're going to include code-style lint rules (i.e., indentation, quotes) in the default ruleset, we should be able to recommend some combination of tools that Just Work™️ and don't run the risk of two things competing against each other

**Comment by rwjblue** [comment]
Agree, but we should most likely fix this in prettier. `{{#link-to` should be treated no differently than `<LinkTo` but it currently is (the `<LinkTo` case would expect the same indentation that the rule currently wants).

**Comment by mike-north** [comment]
> Agree, but we should most likely fix this in prettier.

SGTM. I'm seeking alignment, and don't have a preference for where the adjustment is made

**Comment by dcyriller** [comment]
I believe this has been fixed in prettier by now: https://github.com/prettier/prettier/blob/1.18.2/tests/glimmer/__snapshots__/jsfmt.spec.js.snap#L63

**Comment by rwjblue** [comment]
Closing this in favor of tracking removal of "stylistic rules" as discussed in #746
