### ISSUE TITLE
no-unbound justification

### ISSUE THREAD

**Issue by Techn1x** [ember-template-lint/ember-template-lint#708]
https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/no-unbound.md

It seems to be justified by the fact that it no longer offers performance benefits, but the other reason to use the unbound helper is to freeze a value that is rendered.

Are there any other justifications for not allowing unbound? Also, what's the alternative to unbound if I don't want a rendered value to change?

**Comment by Turbo87** [comment]
you can always do something like `this.set('unboundValue', this.boundValue);` in the constructor of a component if you don't want it to change while the component is rendered

**Comment by amk221** [comment]
What about this use case, not supported by @Turbo87's suggestion

https://ember-twiddle.com/ab1d510483ac0578db12b8eed73087ce?openFiles=routes.application%5C.js%2C&route=%2F%3Fq%3DI%2520am%2520ing%2520into%2520a%2520box

**Comment by Turbo87** [comment]
I have a hard time understanding that twiddle and I can't find an `unbound` anywhere inside of the template?

**Comment by amk221** [comment]
Sorry I should have elaborated, it's really very simple:

```
- A text field, bound to a query parameter
- Type in the text field
- Query parameter is updated
- Model hook is refreshed for new results
- Input is rendered with @value={{this.query}}
```

There is no use of `unbound`, that is the point. It's 'broken' without the user of `unbound`

**Comment by Turbo87** [comment]
I'm still not sure I understand what you're trying to do, but it sounds like https://api.emberjs.com/ember/3.17/classes/@ember%2Fobject%2Fcomputed/methods/oneWay?anchor=oneWay might help in this case 🤷‍♂️

**Comment by amk221** [comment]
It's as basic as you can get for a search page?

**Comment by amk221** [comment]
`oneWay` doesn't help here

**Comment by bertdeblock** [comment]
Hi @amk221, I'm trying to understand your issue.
So in your case, you would use the `{{unbound}}` helper like so to resolve the issue (?):

```hbs
<input
  value={{unbound this.q}}
  {{on "input" this.handleInputQuery}}
>
```

If so, turning this into a component and setting the value in the constructor [as suggested here](https://github.com/ember-template-lint/ember-template-lint/issues/708#issuecomment-559957902) would result in the same behaviour.

Unless I'm misunderstanding how/where you would use `{{unbound}}`.

**Comment by amk221** [comment]
Yeh I think it's safe to ignore me
