### ISSUE TITLE
Ember-template-lint won't lint if Doctype is added.

### ISSUE THREAD

**Issue by meetDeveloper** [ember-template-lint/ember-template-lint#719]
If I add `<!DOCTYPE html>` in the start of file, it will give error 
`error  A block may only be used inside an HTML element or another block. `.

My Config file is
```
module.exports = {
     rules: {
        'no-quoteless-attributes': true,
    }
  }
```
My handlebars template is
```
<!DOCTYPE html>
 <body>
    <div class="container-fluid">
      <div class="main-account-chooser">
        <div class="card">
          <div class="logo"></div>

          <div class="heading">
            <h4>Choose an account to continue</h4>
          </div>

          <div>
            <div title=username class="username">{{username}}</div>
            <a class="card-add-account" tabindex="{{tabindex}}" href="{{loginURL}}">
              <div class="icon-add-alt icon-sm"></div>
              <div class="info"> Add a new account </div>
            </a>
          </div>

        </div>
      </div>
    </div>
  </body>
</html>
```

If I remove `!DOCTYPE`, it will properly lint and give me warning that attribute is not wrapped in quotes.

**Comment by meetDeveloper** [comment]
[It relates to this issue.](https://github.com/emberjs/ember.js/issues/16752)

**Comment by rwjblue** [comment]
This is ultimately a bug in simple-html-tokenizer / glimmer-vm I believe. Specifically, we need to specially handle `<!DOCTYPE` (or perhaps `<!` is specifically defined in the HTML spec, I'd have to look into it).

**Comment by meetDeveloper** [comment]
@rwjblue Yes, It is a bug in glimmer-vm, as far as I know.

**Comment by rwjblue** [comment]
@cvx - Sorry to pester you, but based on your recent work over in simple-html-tokenizer / glimmer-vm I thought maybe you might be willing to poke at this one?

**Comment by CvX** [comment]
@rwjblue sure! 🙂

@meetDeveloper 
1. Can I ask what's the use case for having doctype/`<html>`/`<body>` in a handlebars file?
2. Is probably a typo, but your example is missing the opening `<html>` between the doctype and `<body>` (it doesn't change the error though).

**Comment by meetDeveloper** [comment]
@CvX We use handlebars with sailsjs, and have doctype to make sure browser handle the page in standard mode.

Missing html opening tag was a typo.

**Comment by CvX** [comment]
> We use handlebars with sailsjs, and have doctype to make sure browser handle the page in standard mode.

Are you using those full-html sailsjs templates in ember? (if you do, could you give an example how they are rendered?)
Or are you just using `ember-template-lint` to lint all hbs templates?

**Comment by meetDeveloper** [comment]
@CvX Yes we are handlebars templates, and then in bootstrap, we compile them and expose them.

**Comment by rwjblue** [comment]
FWIW, I made a PR over at https://github.com/tildeio/simple-html-tokenizer/pull/71 to begin working on the fix for this.

**Comment by MelSumner** [comment]
@rwjblue is this still an issue?

**Comment by locks** [comment]
I just tried to reproduce in the current version and confirmed it is fixed!
