### ISSUE TITLE
Deprecate 'img-alt-attributes' rule

### ISSUE THREAD

**Issue by MelSumner** [ember-template-lint/ember-template-lint#739]
Deprecate 'img-alt-attributes' rule since it's been replaced by a more complete/universal rule, 'require-valid-alt-text'.

**Comment by rwjblue** [comment]
For context, there is already some infrastructure for deprecating rules. I _believe_ that we have to add to something like the following to the `DEPRECATED_RULES` `Map` in `lib/helpers/deprecated-rules.js`:

```js
  ['img-alt-attributes', 'require-valid-alt-text'],
```
