### ISSUE TITLE
add new rule: no-forbidden-elements

### ISSUE THREAD

**Issue by MelSumner** [ember-template-lint/ember-template-lint#747]
- disallow use of meta, style, html and script tags in template files. 
- rule should be configurable so teams can add their own disallowed elements

**Comment by rajasegar** [comment]
@MelSumner How this is different from `no-obsolete-elements` rule?
Also the existing rule is not configurable, can this be added as an enhancement for the same?

**Comment by rwjblue** [comment]
FWIW, I think the definition of "obsolete" infers that it should not be configurable (it refers to a specific / concrete set of declared "obsolete" elements).

I think `no-forbidden-elements` _should_ accept configuration (along with having a default set).

**Comment by rajasegar** [comment]
@bmish I am picking this one, can you please assign it to me?
