### ISSUE TITLE
[Feature Request] Add --fix option

### ISSUE THREAD

**Issue by Alonski** [ember-template-lint/ember-template-lint#760]
Adding the feature to autofix template lint rule errors would be nice.

We should add the underlying infrastructure so that rules can be autofixed similar to how ESLint does autofixing with --fix.

Related to:
https://github.com/ember-template-lint/ember-template-lint/issues/305

**Comment by rwjblue** [comment]
Ya, I'm definitely in favor. I'd like to at least _try_ to leverage the work done in ember-template-lint/ember-template-recast to support "safer" fixers. 

The initial rough scope of this would be to:

* Add a hook to the plugin class that folks can implement to handle fixing
* Add a new `--fix` flag to the executable

**Comment by rwjblue** [comment]
Would definitely love for help experimenting / pushing this forward.

**Comment by rwjblue** [comment]
With the (relatively) recent revamp of ember-template-recast, I'd like to consider using it as the fixing mechanism for rules.

Basically, a rule would indicate that a given error is fixable (something akin to what ESLint rules do), and when the `--fix` option is passed ember-template-lint would:

1) gather the errors (without fixing)
2) run the fixer for each of the rules that had errored (in series)
3) gather remaining errors and print to the console

**Comment by dcyriller** [comment]
:wave: I've started to work on this.

**Comment by rwjblue** [comment]
FWIW, I chatted a bit with @dcyriller on this in discord this week. I think we have a rough path forward. I'll try to summarize here:

* Migrate this library to use ember-template-recast as its underlying parser (from `@glimmer/syntax`)
* Add a new optional `fixer` property to the object that is passed to `this.log`. 
* Add a new `--fix` flag to the bin script
* When `ember-template-lint --fix **/*.hbs` is ran, do _roughly_ the following algorithm:
  * assume `--json` in the bin script
  * gather the JSON results
  * get a list of the failures that have a `fixer` property
  * for each file that has an available `fixer`, for each rule
    * instantiate the Rule again
    * use `ember-template-recast`'s `traverse` passing it the result of `ruleInstance.getVisitor()`
    * immediately invoke `fixer()`
    * loop :D
  * run the normal linting again, printing the results (or honoring the original --json flag state)
* Create a meta issue to evaluate each rule for "fixability"

I _believe_ that @dcyriller is still planning on working on this, but figured it would be good to get the general shape of the proposed solution "out there" in case there are fundamental issues that others spot...

**Comment by rwjblue** [comment]
For those following along here, there has been a bit of progress. #873 just landed into the `next` branch (will become v2.0.0 "soon"). Once that is done, we are ready to begin actually prototyping the `--fix` support.

**Comment by lifeart** [comment]
eslint ref: https://eslint.org/docs/developer-guide/working-with-plugins#processors-in-plugins

**Comment by dcyriller** [comment]
@rwjblue I've continued the --fix implementation in these two PRs: https://github.com/ember-template-lint/ember-template-lint/pull/935 and https://github.com/ember-template-lint/ember-template-lint/pull/1025

I have a main blocker though, mentionned in the second PR: I miss a `ranges` concept in the AST. Currently, we have a `location` (eg. [{ start: {line:2, column:2}, end: {line:2, column: 4}}]). But no "range" (eg. `[24, 26]`). I feel that having this sort of absolute positioning is necessary to actually edit the file.

Do you have any advice on where (and how?) to implement it?
