### ISSUE TITLE
add new rule: no-obscure-hbs

### ISSUE THREAD

**Issue by efx** [ember-template-lint/ember-template-lint#787]
Originally opened in https://github.com/ember-template-lint/ember-cli-template-lint/issues/437
I have some handlebars syntax in my application that "works", but is "wrong".
[Twiddle](https://ember-twiddle.com/07c76e285823a864ecfd1a59dc754705?openFiles=templates.application.hbs%2C)
```hbs
<p>some user name {{this.list.[0].name}}</p>
```

locks and rwjblue proposed adding a template rule to warn/error before any deprecations. ( see [ember-cli discord](https://discordapp.com/channels/480462759797063690/486548111221719040) on 2/06/19)

**Comment by rwjblue** [comment]
Thanks for reporting! I think we should probably make rules for the individual "issues" that we have, otherwise adding new scenarios will be a "breaking change".
