### ISSUE TITLE
Add test ensuring new rule setup is correct.

### ISSUE THREAD

**Issue by rwjblue** [ember-template-lint/ember-template-lint#797]
I keep forgetting some of the basic setup work for adding a new rule (thanks to @bmish for catching my mistakes). In order to save us from my forgetfulness we should add a test to ensure this kind of thing doesn't slip. 

Basically to assert the following:

* All files under `lib/rules/` (except `base.js` and `index.js`) exist as values in the `lib/rules/index.js` reexport.
* All files under `lib/rules/` (same exception) have a corresponding `docs/rule/` file.
* All files under `docs/rule/` have a link from `docs/rules.md`.

**Comment by lifeart** [comment]
On it

**Comment by rwjblue** [comment]
I think this was resolved by #798
