### ISSUE TITLE
Default rules for 'octane' config contain conflicting recommendations

### ISSUE THREAD

**Issue by pgengler** [ember-template-lint/ember-template-lint#804]
Using the `octane` config, both the "no-action-modifiers" and "no-element-event-actions" rules are enabled; I'm guessing the idea is to encourage use of `{{on ...}}` but the recommendations for these rules don't get along:

The no-action-modifiers error says to use `onclick`:
> `action` modifiers should not be used (use `onclick` attributes instead).  no-action-modifiers

While no-element-event-action says to use `{{action ...}}`:
> Use Ember `{{action ...}}` helper instead of HTML element event properties like `onclick`.  no-element-event-actions

**Comment by bmish** [comment]
Also suggested in #746. I opened a fix.

**Comment by rwjblue** [comment]
Sorry about the somewhat bad experience here. Thank you for reporting (and @bmish for jumping on it).
