### ISSUE TITLE
Use `.editorconfig` for indentation

### ISSUE THREAD

**Issue by lougreenwood** [ember-template-lint/ember-template-lint#901]
It would be useful if the config value for line indentation were pulled from the `.editorconfig` file, if it exists.

**Comment by rwjblue** [comment]
Similar to #284. I think to move forward we need to be able to parse the `.editorconfig` file, if anyone has the bandwidth I think digging in to take a look at how easy or hard that would be is a great next step.

**Comment by lifeart** [comment]
https://www.npmjs.com/package/editorconfig

**Comment by rwjblue** [comment]
This was resolved in #918 / #906, and is released in 2.0.0-beta.2.
