### ISSUE TITLE
New Feature: allow multiple presets

### ISSUE THREAD

**Issue by MelSumner** [ember-template-lint/ember-template-lint#924]
Allow multiple presets to be included, so we can make multiple recommended sets. 

Example: I'd like to make a a11y-strict preset, which will check for a lot more things and is a lot more strict about how things are done. 

This will also require tags/meta data to be added to each rule, to define which preset it belongs to.

**Comment by dcyriller** [comment]
Would it make sense to extract a11y-related rules in a plugin. Users could have a config akin to:
```
module.exports = {
  plugins: ["ember-template-lint-plugin-a11y"],

  extends: ["recommended", "ember-template-lint-plugin-a11y:strict"],
  // or 
  extends: ["recommended", "ember-template-lint-plugin-a11y:all"],
};
```
where `strict` and `all` would be sets in the external plugin.
