### ISSUE TITLE
Allow setting no-action rule to `warning` severity

### ISSUE THREAD

**Issue by mehulkar** [ember-template-lint/ember-template-lint#939]
Not entirely clear if I'm doing this right (#936), but I was unable to set the warning level for the `no-action` rule to Warning severity. I think a `parseConfig` needs to be implemented for the rule? Or something in the constructor of that rule class to set the severity? I couldn't figure out any other examples of Warning severity except for *modules* being set as "pending".

**Comment by Turbo87** [comment]
I don't think a "severity level" is currently supported by ember-template-lint 🤔

**Comment by Turbo87** [comment]
closing in favor of #936
