### ISSUE TITLE
Allow on "load" and on "error" modifiers for img tags

### ISSUE THREAD

**Issue by mehulkar** [ember-template-lint/ember-template-lint#940]
The `no-invalid-interactive` rule currently throws for this code in 1.8.2. I think this should be allowed?

```hbs
<img {{on "load" this.onLoad}} {{on "error" this.onError}}>
```

Looking at the lint rule, there are exceptions for the `onload` and `onerror` attributes, so I think the modifer version of this could also be added. 

https://github.com/ember-template-lint/ember-template-lint/blob/v1.8.2/lib/rules/lint-no-invalid-interactive.js#L114-L117

**Comment by rwjblue** [comment]
Yep, seems like a good bugfix to me.

**Comment by lifeart** [comment]
on it

**Comment by MelSumner** [comment]
Thank you for fixing the issue @lifeart :+1:
