### ISSUE TITLE
Support external output formatters (eslint style)

### ISSUE THREAD

**Issue by velrest** [ember-template-lint/ember-template-lint#961]
###  `--format -f <format_or_package_path>`

In addition to the `--json` flag i would implement a `--format -f <format_or_package_path>` flag.
If unset the output is the standard human readable text output and `--json` would then be a alias for `--format json`.

If the passed path is a js file / node_module we would import it and assume the default import is a function which takes the errors object and returns the formatted output.

The use case would be f.e. to support editors which have a custom format for linting errors. In my case this is the [kakoune](github.com/mawww/kakoune) editor. There exists [a formatter for eslint](https://github.com/Delapouite/eslint-formatter-kakoune) and my idea would be to implement the formatting param in `ember-template-lint` so i could use `ember-template-lint` in kakoune.

What do you think, is there a use case for this or is this too specific to my problem?

**Comment by rwjblue** [comment]
I'm not sure what the exact implementation would look like, but it definitely seems like a good idea to me.

**Comment by Bouke** [comment]
I would also suggest matching eslint's json format, so that we can reuse tools that can already work with eslint's json output. (e.g. SonarQube)

**Comment by scalvert** [comment]
Implemented in #1340
