### ISSUE TITLE
no-invalid-interactive and ARIA-role `grid`

### ISSUE THREAD

**Issue by abel-n** [ember-template-lint/ember-template-lint#981]
According to [MDN web docs](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Grid_Role) an interactive table-like (or, better said, grid-like) widget with two-dimensional navigation should have the role `grid` but I don't see that in [is-interactive-element.js](https://github.com/ember-template-lint/ember-template-lint/blob/ef3cd10b6a9e1017ceb33e06f16ed30a3c585c9e/lib/helpers/is-interactive-element.js#L19) as a widget role.

Shouldn't it be included?

**Comment by rwjblue** [comment]
Ya, we got the original list of roles from [here](https://www.w3.org/TR/wai-aria-1.1/#widget_roles), but it looks like we didn't include the roles for composite widgets.

Would love a PR fixing.

/cc @MelSumner

**Comment by locks** [comment]
The PR to address this issue was ultimately decided against, so I'll be closing this issue. Consult https://github.com/ember-template-lint/ember-template-lint/pull/984 for the in-depth discussion!
