### ISSUE TITLE
[1.9.0] error  Cannot use 'in' operator to search for 'max' in true  undefined

### ISSUE THREAD

**Issue by boris-petrov** [ember-template-lint/ember-template-lint#983]
The new `no-multiple-empty-lines` rule outputs an error when enabled:

```
frontend/templates/foo.hbs
  -:-  error  Cannot use 'in' operator to search for 'max' in true  undefined
```

**Comment by rwjblue** [comment]
Is there anything special in `foo.hbs`?

**Comment by rwjblue** [comment]
Looks like there is no config normalization in that rule (it is a new addition), so when you specify `true` as a config value it throws this error:

https://github.com/ember-template-lint/ember-template-lint/blob/master/lib/rules/no-multiple-empty-lines.js#L24

We need to update `no-multiple-empty-lines` to implement `parseConfig` to normalize `true` to ` { max: 1 }` (then that `in` check can be removed completely).

@Turbo87 - Think you might have a minute to poke at this?

**Comment by Turbo87** [comment]
ouch! sorry about that. I'll have a look.
