### ISSUE TITLE
Replace whitelist/blacklist references

### ISSUE THREAD

**Issue by MelSumner** [ember-template-lint/ember-template-lint#989]
Replace instances of whitelist & blacklist with more inclusive alternatives. Suggest "allowed" and "disallowed".

**Comment by jaydgruber** [comment]
I would like to pick this up. I propose using `allowlist` & `denylist` to be consistent w/ Eslint terminology for same. ref: https://eslint.org/docs/user-guide/configuring#eslintignore

I think we could add `'id-denylist': ['error', 'whitelist', 'blacklist'],` to our `.eslintrc` to catch future occurrences. ref: [eslint/id-denylist](https://eslint.org/docs/rules/id-denylist)
